// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Flow from "./Flow.res.mjs";
import * as Html from "./Html.res.mjs";
import * as Scan from "./Scan.res.mjs";
import * as Write from "./Write.res.mjs";
import * as Screen from "./Screen.res.mjs";
import * as States from "./States.res.mjs";
import * as Markdown from "./Markdown.res.mjs";
import * as Sequence from "./Sequence.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let common = [
  [
    "note",
    "Note"
  ],
  [
    "draft",
    "Draft"
  ],
  [
    "settled",
    "Settled"
  ],
  [
    "open",
    "Open question"
  ],
  [
    "technical",
    "Technical"
  ],
  [
    "principle",
    "Principle"
  ],
  [
    "rejected",
    "Rejected"
  ]
];

let quoteInfo = new RegExp("^quote(?:\\s+\"([^\"]*)\")?(?:\\s+(\\S.*?))?\\s*$");

function context(options) {
  let callouts = Object.fromEntries(Belt_Array.concatMany([
    common,
    Stdlib_Option.mapOr(options.callouts, [], prim => Object.entries(prim))
  ]));
  let extras = Stdlib_Option.getOr(options.extra, []);
  let isFence = e => Stdlib_Option.getOr(e.fence, false);
  return {
    md: Markdown.make(options.markdown),
    callouts: callouts,
    owners: Stdlib_Option.getOr(Stdlib_Option.flatMap(options["ui-dialog"], d => d.owners), {}),
    sequenceKinds: Stdlib_Option.getOr(Stdlib_Option.flatMap(options.sequence, k => k.kinds), {}),
    statesKinds: Stdlib_Option.getOr(Stdlib_Option.flatMap(options.states, k => k.kinds), {}),
    extras: extras,
    names: {
      containers: Belt_Array.concatMany([
        Object.keys(callouts),
        [
          "quote",
          "flow",
          "ui-dialog",
          "ui-flow"
        ],
        extras.filter(e => !Stdlib_Option.getOr(e.fence, false)).map(e => e.name)
      ]),
      fences: Belt_Array.concatMany([
        [
          "sequence",
          "states"
        ],
        extras.filter(isFence).map(e => e.name)
      ])
    }
  };
}

function caption(info) {
  if (info === "") {
    return;
  } else {
    return info;
  }
}

function readIn(ctx, source, offset) {
  return Scan.scan(source, offset, ctx.names).map(item => {
    if (item.TAG === "Run") {
      return {
        TAG: "Markdown",
        _0: item._0
      };
    }
    let line = item.line;
    let body = item.body;
    let info = item.info;
    let name = item.name;
    let inner = () => readIn(ctx, body, line + 1 | 0);
    switch (name) {
      case "flow" :
        return Flow.read(ctx.md, body, "Flow");
      case "quote" :
        let m = quoteInfo.exec((`quote ` + info).trim());
        if (m == null) {
          return Html.fail(`Unknown block on line ` + line.toString() + `: quote ` + info);
        } else {
          return {
            TAG: "Quote",
            author: Sequence.capture(m, 0),
            date: Sequence.capture(m, 1),
            children: inner()
          };
        }
      case "sequence" :
        return {
          TAG: "Sequence",
          _0: Sequence.read(body, caption(info), ctx.sequenceKinds)
        };
      case "states" :
        return {
          TAG: "States",
          _0: States.read(body, caption(info), ctx.statesKinds)
        };
      case "ui-dialog" :
        return Screen.read(info, body, ctx.owners);
      case "ui-flow" :
        return {
          TAG: "Screens",
          caption: caption(info),
          children: inner()
        };
      default:
        let label = ctx.callouts[name];
        if (label !== undefined) {
          return {
            TAG: "Callout",
            name: name,
            label: label,
            children: inner()
          };
        } else {
          return {
            TAG: "Extra",
            name: name,
            info: info,
            body: body
          };
        }
    }
  });
}

function renderIn(ctx, nodes, env) {
  return nodes.map(node => {
    switch (node.TAG) {
      case "Markdown" :
        return ctx.md.render(node._0, env);
      case "Callout" :
        let label = Html.escape(node.label);
        return `<aside class="callout callout--` + node.name + `" aria-label="` + label + `"><p class="callout__label">` + label + `</p><div class="callout__body">\n` + renderIn(ctx, node.children, env) + `</div></aside>\n`;
      case "Quote" :
        let parts = Stdlib_Array.keepSome([
          Stdlib_Option.map(node.author, a => `<cite>` + Html.escape(a) + `</cite>`),
          Stdlib_Option.map(node.date, d => `<span class="quote__date">` + Html.escape(d) + `</span>`)
        ]);
        let under = Primitive_object.equal(parts, []) ? "" : `<figcaption>— ` + parts.join(", ") + `</figcaption>`;
        return `<figure class="quote"><blockquote>\n` + renderIn(ctx, node.children, env) + `</blockquote>` + under + `</figure>\n`;
      case "Flow" :
        return Flow.render(ctx.md, node.label, node.columns);
      case "Dialog" :
        return Screen.render(ctx.md, node.owner, node.title, node.widgets);
      case "Screens" :
        return Screen.renderFlow(node.caption, renderIn(ctx, node.children, env));
      case "Sequence" :
        return Sequence.render(node._0) + "\n";
      case "States" :
        return States.render(node._0) + "\n";
      case "Extra" :
        let name = node.name;
        let e = ctx.extras.find(e => e.name === name);
        if (e !== undefined) {
          return e.render(node.info, node.body);
        } else {
          return "";
        }
    }
  }).join("");
}

function read(source, options) {
  return readIn(context(options), source, 1);
}

function render(nodes, options) {
  let ctx = context(options);
  return renderIn(ctx, nodes, Markdown.env());
}

function blocks(options) {
  let ctx = context(options);
  return source => {
    let env = Markdown.env();
    ctx.md.parse(source, env);
    return renderIn(ctx, readIn(ctx, source, 1), env);
  };
}

let write = Write.write;

export {
  read,
  write,
  render,
  blocks,
}
/* quoteInfo Not a pure module */
