// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Markdown from "./Markdown.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function lists(md, body) {
  let top = [];
  let openLists = [];
  let openItems = [];
  md.parse(body, Markdown.env()).forEach(token => {
    let match = token.type;
    switch (match) {
      case "inline" :
        return Stdlib_Option.forEach(openItems.at(-1), item => {
          if (Stdlib_Option.isNone(item.text)) {
            item.text = token.content;
            return;
          }
        });
      case "list_item_close" :
        openItems.pop();
        return;
      case "list_item_open" :
        let item = {
          text: undefined,
          lists: []
        };
        Stdlib_Option.forEach(openLists.at(-1), list => {
          list.items.push(item);
        });
        openItems.push(item);
        return;
      case "bullet_list_close" :
      case "ordered_list_close" :
        openLists.pop();
        return;
      case "bullet_list_open" :
      case "ordered_list_open" :
        break;
      default:
        return;
    }
    let list_ordered = token.type === "ordered_list_open";
    let list_items = [];
    let list = {
      ordered: list_ordered,
      items: list_items
    };
    let item$1 = openItems.at(-1);
    if (item$1 !== undefined) {
      item$1.lists.push(list);
    } else {
      top.push(list);
    }
    openLists.push(list);
  });
  return top;
}

let bold = new RegExp("^(?:\\*\\*(.+)\\*\\*|__(.+)__)$");

function title(text) {
  let m = bold.exec(text);
  if (m == null) {
    return text;
  } else {
    return Stdlib_Option.getOr(Stdlib_Array.keepSome(m.slice(1))[0], text);
  }
}

function ordered(item) {
  return item.lists.find(l => l.ordered);
}

function step(item) {
  return {
    text: Stdlib_Option.getOr(item.text, ""),
    details: Stdlib_Option.mapOr(item.lists.find(l => !l.ordered), [], l => l.items.map(i => Stdlib_Option.getOr(i.text, "")))
  };
}

function read(md, body, label) {
  let list = lists(md, body).find(l => l.ordered);
  let list$1 = list !== undefined ? list : Html.fail("flow: a flow is a numbered list");
  let columns = list$1.items.some(item => Stdlib_Option.isSome(ordered(item))) ? list$1.items.map(item => ({
      title: Stdlib_Option.map(item.text, title),
      steps: Stdlib_Option.mapOr(ordered(item), [], l => l.items.map(step))
    })) : [{
        title: undefined,
        steps: list$1.items.map(step)
      }];
  return {
    TAG: "Flow",
    label: label,
    columns: columns
  };
}

function render(md, label, columns) {
  let inline = text => md.renderInline(text, Markdown.env());
  let step = s => {
    let details = Primitive_object.equal(s.details, []) ? "" : `\n<ul class="flow__details">\n` + s.details.map(d => `<li>` + inline(d) + `</li>`).join("\n") + `\n</ul>`;
    return `<li class="flow__step"><p class="flow__text">` + inline(s.text) + `</p>` + details + `\n</li>`;
  };
  let column = c => `<li class="flow__column">` + Stdlib_Option.mapOr(c.title, "", t => `<p class="flow__title">` + inline(t) + `</p>`) + `\n<ol class="flow__steps">\n` + c.steps.map(step).join("\n") + `\n</ol>\n</li>`;
  let label$1 = Html.escape(label);
  return `<aside class="callout callout--flow" aria-label="` + label$1 + `"><p class="callout__label">` + label$1 + `</p><div class="callout__body">\n<ol class="flow">\n` + columns.map(column).join("\n") + `\n</ol>\n</div></aside>\n`;
}

export {
  lists,
  bold,
  title,
  ordered,
  step,
  read,
  render,
}
/* bold Not a pure module */
