// Generated by ReScript, PLEASE EDIT WITH CARE

import MarkdownIt from "markdown-it";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import MarkdownItAnchor from "markdown-it-anchor";

function env() {
  return {};
}

let rawSetup = ((md) => {
  const code = md.renderer.rules.code_inline
  md.renderer.rules.code_inline = (tokens, index, options, env, self) => {
    const content = tokens[index].content
    if (!content.startsWith("!")) return code(tokens, index, options, env, self)
    // The "!" and the one space after it are not shown.
    return '<code class="code--mark">' + md.utils.escapeHtml(content.replace(/^! ?/, "")) + "</code>"
  }
  md.renderer.rules.table_open = () => '<div class="table-wrap"><table>\n'
  md.renderer.rules.table_close = () => "</table></div>\n"
});

let marks = new RegExp("[\\u0300-\\u036f]", "g");

let others = new RegExp("[^a-z0-9]+", "g");

let ends = new RegExp("^-|-$", "g");

function slugify(text) {
  return text.normalize("NFD").replace(marks, "").toLowerCase().replace(others, "-").replace(ends, "");
}

function make(extend) {
  let md = new MarkdownIt({
    html: false,
    linkify: true
  });
  rawSetup(md);
  md.use(MarkdownItAnchor, {
    level: [
      2,
      3
    ],
    slugify: slugify
  });
  Stdlib_Option.forEach(extend, f => f(md));
  return md;
}

export {
  env,
  rawSetup,
  marks,
  others,
  ends,
  slugify,
  make,
}
/* marks Not a pure module */
