// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let codeLine = new RegExp("^\\s{0,3}(`{3,}|~{3,})(.*)$");

let colonLine = new RegExp("^\\s*(:{3,})\\s*(.*?)\\s*$");

let space = new RegExp("\\s+");

function capture(m, index) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(m.slice(1)[index], x => x), "");
}

function split(text) {
  let text$1 = text.trim();
  let at = text$1.search(space);
  if (at !== -1) {
    return [
      text$1.slice(0, at),
      text$1.slice(at).trim()
    ];
  } else {
    return [
      text$1,
      ""
    ];
  }
}

function fenceEnd(lines, start, marker) {
  let char = marker.charAt(0);
  let _index = start + 1 | 0;
  while (true) {
    let index = _index;
    let line = lines[index];
    if (line === undefined) {
      return index;
    }
    let m = codeLine.exec(line);
    if (m == null) {
      _index = index + 1 | 0;
      continue;
    }
    if (capture(m, 0).charAt(0) === char && capture(m, 0).length >= marker.length && capture(m, 1).trim() === "") {
      return index;
    }
    _index = index + 1 | 0;
    continue;
  };
}

function blockEnd(lines, start, marker, offset) {
  let depth = [marker.length];
  let _index = start + 1 | 0;
  while (true) {
    let index = _index;
    let line = lines[index];
    if (line === undefined) {
      return Html.fail(`Unclosed block on line ` + (offset + start | 0).toString());
    }
    let m = codeLine.exec(line);
    if (m == null) {
      let m$1 = colonLine.exec(line);
      if (m$1 == null) {
        _index = index + 1 | 0;
        continue;
      }
      if (capture(m$1, 1) !== "") {
        depth.push(capture(m$1, 0).length);
        _index = index + 1 | 0;
        continue;
      }
      let opened = Stdlib_Option.getOr(depth.pop(), 0);
      if (capture(m$1, 0).length < opened) {
        Html.fail(`Mismatched block close on line ` + (offset + index | 0).toString());
      }
      if (depth.length === 0) {
        return index;
      }
      _index = index + 1 | 0;
      continue;
    }
    _index = fenceEnd(lines, index, capture(m, 0)) + 1 | 0;
    continue;
  };
}

function blank(line) {
  return line.trim() === "";
}

function trimmed(lines) {
  let first = lines.findIndex(line => line.trim() !== "");
  let last = lines.findLastIndex(line => line.trim() !== "");
  if (first < 0) {
    return;
  } else {
    return lines.slice(first, last + 1 | 0).join("\n");
  }
}

function scan(text, offset, names) {
  let lines = text.split("\n");
  let items = [];
  let run = [];
  let flush = () => {
    Stdlib_Option.forEach(trimmed(run), text => {
      items.push({
        TAG: "Run",
        _0: text
      });
    });
    run.splice(0, run.length);
  };
  let slice = (start, end) => lines.slice(start, end).join("\n");
  let go = _index => {
    while (true) {
      let index = _index;
      let line = lines[index];
      if (line === undefined) {
        return flush();
      }
      let m = codeLine.exec(line);
      if (m == null) {
        let m$1 = colonLine.exec(line);
        if (m$1 == null) {
          run.push(line);
          _index = index + 1 | 0;
          continue;
        }
        if (capture(m$1, 1) === "") {
          return Html.fail(`Mismatched block close on line ` + (offset + index | 0).toString());
        }
        let match = split(capture(m$1, 1));
        let name = match[0];
        if (!names.containers.includes(name)) {
          Html.fail(`Unknown block on line ` + (offset + index | 0).toString() + `: ` + name);
        }
        let end = blockEnd(lines, index, capture(m$1, 0), offset);
        flush();
        items.push({
          TAG: "Block",
          name: name,
          info: match[1],
          body: slice(index + 1 | 0, end),
          line: offset + index | 0
        });
        _index = end + 1 | 0;
        continue;
      }
      let end$1 = fenceEnd(lines, index, capture(m, 0));
      let match$1 = split(capture(m, 1));
      let word = match$1[0];
      if (names.fences.includes(word)) {
        flush();
        items.push({
          TAG: "Block",
          name: word,
          info: match$1[1],
          body: slice(index + 1 | 0, end$1),
          line: offset + index | 0
        });
      } else {
        lines.slice(index, end$1 + 1 | 0).forEach(l => {
          run.push(l);
        });
      }
      _index = end$1 + 1 | 0;
      continue;
    };
  };
  go(0);
  return items;
}

let fail = Html.fail;

export {
  fail,
  codeLine,
  colonLine,
  space,
  capture,
  split,
  fenceEnd,
  blockEnd,
  blank,
  trimmed,
  scan,
}
/* codeLine Not a pure module */
