// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Scan from "./Scan.res.mjs";
import * as Markdown from "./Markdown.res.mjs";
import * as Sequence from "./Sequence.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let buttonLine = new RegExp("^(?:(?:\\[\\[[^\\[\\]]+\\]\\]|\\[[^\\[\\]]+\\])\\*?\\s*)+$");

let optionLine = new RegExp("^(\\( \\)|\\(x\\)|\\[ \\]|\\[x\\])\\s+(\\S.*)$", "i");

let fieldLine = new RegExp("^(\\S.*?)\\s*:\\s*_{3,}$");

let blankLine = new RegExp("\\n[ \\t]*\\n");

let buttons = ((line) =>
  [...line.matchAll(/\[\[([^\[\]]+)\]\](\*?)|\[([^\[\]]+)\](\*?)/g)].map(
    ([, primary, primaryClick, plain, plainClick]) => ({
      text: (primary ?? plain).trim(),
      primary: primary !== undefined,
      clicked: Boolean(primaryClick || plainClick),
    }),
  ));

function widget(line) {
  if (buttonLine.test(line) || optionLine.test(line)) {
    return true;
  } else {
    return fieldLine.test(line);
  }
}

function paragraph(source) {
  let lines = source.split("\n").map(prim => prim.trim());
  if (!lines.some(widget)) {
    return [{
        TAG: "Text",
        _0: source
      }];
  }
  let parts = [];
  let text = [];
  let options = [];
  let flush = () => {
    if (Primitive_object.notequal(text, [])) {
      parts.push({
        TAG: "Text",
        _0: text.join("\n")
      });
    }
    if (Primitive_object.notequal(options, [])) {
      parts.push({
        TAG: "Options",
        _0: options.slice()
      });
    }
    text.splice(0, text.length);
    options.splice(0, options.length);
  };
  lines.forEach(line => {
    if (buttonLine.test(line)) {
      flush();
      parts.push({
        TAG: "Actions",
        _0: buttons(line)
      });
      return;
    }
    let match = optionLine.exec(line);
    let match$1 = fieldLine.exec(line);
    if (match == null) {
      if (match$1 == null) {
        if (Primitive_object.notequal(options, [])) {
          flush();
        }
        text.push(line);
      } else {
        flush();
        parts.push({
          TAG: "Field",
          _0: Stdlib_Option.getOr(Sequence.capture(match$1, 0), "")
        });
      }
      return;
    }
    if (Primitive_object.notequal(text, [])) {
      flush();
    }
    let mark = Stdlib_Option.getOr(Sequence.capture(match, 0), "");
    options.push({
      text: Stdlib_Option.getOr(Sequence.capture(match, 1), ""),
      radio: mark.startsWith("("),
      on: mark.charAt(1).toLowerCase() === "x"
    });
  });
  flush();
  return parts;
}

function read(info, body, owners) {
  let match = Scan.split(info);
  let first = match[0];
  let label = owners[first];
  let match$1 = label !== undefined ? [
      [
        first,
        label
      ],
      match[1]
    ] : [
      undefined,
      info
    ];
  let title = match$1[1];
  let widgets = Stdlib_Array.filterMap(body.split(blankLine), p => p).filter(p => p.trim() !== "").flatMap(p => paragraph(p.trim()));
  return {
    TAG: "Dialog",
    owner: match$1[0],
    title: title === "" ? undefined : title,
    widgets: widgets
  };
}

function render(md, owner, title, widgets) {
  let inline = text => md.renderInline(text, Markdown.env());
  let part = w => {
    switch (w.TAG) {
      case "Text" :
        return md.render(w._0, Markdown.env());
      case "Actions" :
        let row = w._0.map(b => `<span class="ui-dialog__button` + (
          b.primary ? " ui-dialog__button--primary" : ""
        ) + (
          b.clicked ? " ui-dialog__button--clicked" : ""
        ) + `">` + Html.escape(b.text) + `</span>`);
        return `<div class="ui-dialog__actions">` + row.join("") + `</div>\n`;
      case "Options" :
        let row$1 = w._0.map(c => `<div class="ui-dialog__option ui-dialog__option--` + (
          c.radio ? "radio" : "check"
        ) + (
          c.on ? " ui-dialog__option--on" : ""
        ) + `">` + inline(c.text) + `</div>`);
        return `<div class="ui-dialog__options">` + row$1.join("") + `</div>\n`;
      case "Field" :
        return `<div class="ui-dialog__field"><span class="ui-dialog__field-label">` + inline(w._0) + `</span><span class="ui-dialog__input"></span></div>\n`;
    }
  };
  let label = Stdlib_Option.mapOr(title, "Screen mockup", t => `Screen mockup: ` + t);
  let bar = Stdlib_Array.keepSome([
    Stdlib_Option.map(owner, param => `<span class="ui-dialog__owner">` + Html.escape(param[1]) + `</span>`),
    Stdlib_Option.map(title, t => `<span class="ui-dialog__title">` + Html.escape(t) + `</span>`)
  ]).join("");
  return `<div class="ui-dialog` + Stdlib_Option.mapOr(owner, "", param => {
    let key = param[0];
    return ` ui-dialog--` + key + `" style="--tone: var(--tone-` + key + `, var(--blocks-ink))`;
  }) + `" role="group" aria-label="` + Html.escape(label) + `">` + (
    bar === "" ? "" : `<div class="ui-dialog__bar">` + bar + `</div>`
  ) + `<div class="ui-dialog__body">\n` + widgets.map(part).join("") + `</div></div>\n`;
}

function renderFlow(caption, inner) {
  return `<figure class="ui-flow">` + Stdlib_Option.mapOr(caption, "", c => `<figcaption class="ui-flow__caption">` + Html.escape(c) + `</figcaption>`) + `<div class="ui-flow__steps">\n` + inner + `</div></figure>\n`;
}

let capture = Sequence.capture;

export {
  buttonLine,
  optionLine,
  fieldLine,
  blankLine,
  buttons,
  capture,
  widget,
  paragraph,
  read,
  render,
  renderFlow,
}
/* buttonLine Not a pure module */
