// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let chars = ((text) => [...text]);

let narrow = chars("iljtfrI'.,:;!|()[]");

let wide = chars("mwMW@");

function width(text, size) {
  return Stdlib_Array.reduce(chars(text), 0, (units, c) => units + (
    narrow.includes(c) ? 0.37 : (
        wide.includes(c) ? 0.94 : 0.53
      )
  )) * size;
}

let defaultKind = "party";

let lineKeys = [
  [
    "message",
    "a message, and what it carries"
  ],
  [
    "refused",
    "a refusal"
  ],
  [
    "state",
    "the state of a party"
  ]
];

let partyCell = new RegExp("^([\\p{L}\\p{N}_.\\-]+)(?::([\\p{L}]+))?$", "u");

let moveLine = new RegExp("^ *(\\S+) +(->|-x) +(\\S+)(?: +(.*))?$");

let stateLine = new RegExp("^ *(\\S+) += +(.+)$");

let directiveLine = new RegExp("^\\{(\\w+)\\}$");

let space = new RegExp("\\s+");

function capture(m, index) {
  return Stdlib_Option.flatMap(m.slice(1)[index], x => x);
}

function readText(text, kinds) {
  let parties = {
    contents: undefined
  };
  let steps = [];
  let legend = {
    contents: false
  };
  text.split("\n").forEach((raw, index) => {
    let line = raw.trimEnd();
    let at = `line ` + (index + 1 | 0).toString();
    if (line.trim() === "" || line.trim().startsWith("#")) {
      return;
    }
    let d = directiveLine.exec(line.trim());
    if (d == null) {
      let match = parties.contents;
      if (match === undefined) {
        parties.contents = line.trim().split(space).map(cell => {
          let cell$1 = Stdlib_Option.getOr(cell, "");
          let m = partyCell.exec(cell$1);
          if (m == null) {
            return Html.fail(`sequence: cannot read the party ` + cell$1 + `, ` + at);
          }
          let kind = Stdlib_Option.getOr(capture(m, 1), defaultKind);
          if (kind !== defaultKind && Stdlib_Option.isNone(kinds[kind])) {
            Html.fail(`sequence: no kind called ` + kind + `, ` + at);
          }
          return {
            name: Stdlib_Option.getOr(capture(m, 0), ""),
            kind: kind
          };
        });
        return;
      }
      let m = stateLine.exec(line);
      if (m == null) {
        let m$1 = moveLine.exec(line);
        if (m$1 == null) {
          return Html.fail(`sequence: cannot read the step at ` + at);
        }
        let from = Stdlib_Option.getOr(capture(m$1, 0), "");
        let to = Stdlib_Option.getOr(capture(m$1, 2), "");
        if (from === to) {
          Html.fail(`sequence: a message runs between two parties, ` + at);
        }
        steps.push({
          TAG: "Said",
          from: from,
          to: to,
          refused: Primitive_object.equal(capture(m$1, 1), "-x"),
          label: Stdlib_Option.getOr(capture(m$1, 3), "").trim()
        });
        return;
      }
      steps.push({
        TAG: "Is",
        on: Stdlib_Option.getOr(capture(m, 0), ""),
        label: Stdlib_Option.getOr(capture(m, 1), "").trim()
      });
      return;
    }
    let name = Stdlib_Option.getOr(capture(d, 0), "");
    if (name !== "legend") {
      Html.fail(`sequence: no directive {` + name + `}, ` + at);
    }
    legend.contents = true;
  });
  let parties$1 = parties.contents;
  let parties$2 = parties$1 !== undefined ? parties$1 : Html.fail("sequence: no parties are named");
  if (parties$2.length < 2) {
    Html.fail("sequence: a sequence runs between two parties at least");
  }
  let named = parties$2.map(p => p.name);
  if (new Set(named).size < parties$2.length) {
    Html.fail("sequence: a party is named twice");
  }
  steps.forEach(step => {
    let ends;
    ends = step.TAG === "Said" ? [
        step.from,
        step.to
      ] : [step.on];
    ends.forEach(end => {
      if (!named.includes(end)) {
        return Html.fail(`sequence: no party called ` + end);
      }
    });
  });
  return [
    parties$2,
    steps,
    legend.contents
  ];
}

function place(parties, steps) {
  let lanes = parties.map((party, index) => ({
    party: party,
    index: index,
    w: Math.ceil(Math.max(84, width(party.name, 13) + 12 * 2)),
    centre: 0,
    x: 0
  }));
  let lane = name => Stdlib_Option.getOrThrow(lanes.find(l => l.party.name === name), undefined);
  let needs = Stdlib_Array.make(parties.length - 1 | 0, 0);
  steps.forEach(step => {
    if (step.TAG !== "Said") {
      return;
    }
    let label = step.label;
    if (label === "") {
      return;
    }
    let to = step.to;
    let from = step.from;
    let low = Math.min(lane(from).index, lane(to).index);
    let high = Math.max(lane(from).index, lane(to).index);
    let need = (width(label, 11) + 12 * 2) / (high - low | 0);
    for (let gap = low; gap < high; ++gap) {
      needs[gap] = Math.max(needs[gap], need);
    }
  });
  lanes.forEach((l, index) => {
    let x;
    if (index > 0) {
      let before = lanes[index - 1 | 0];
      let apart = Math.max(64 + (before.w + l.w) / 2, needs[index - 1 | 0]);
      x = before.centre + apart;
    } else {
      x = l.w / 2;
    }
    l.centre = Math.round(x);
    l.x = l.centre - l.w / 2;
  });
  return [
    lanes,
    lane
  ];
}

function unique(items) {
  return Stdlib_Array.reduce(items, [], (seen, item) => {
    if (seen.includes(item)) {
      return seen;
    } else {
      return Belt_Array.concatMany([
        seen,
        [item]
      ]);
    }
  });
}

function read(text, caption, kinds) {
  let match = readText(text, kinds);
  let steps = match[1];
  let parties = match[0];
  let match$1 = place(parties, steps);
  let lane = match$1[1];
  let lanes = match$1[0];
  let bottom = 26 + 24 + steps.length * 32;
  let heads = lanes.map(l => ({
    TAG: "Head",
    kind: l.party.kind,
    x: l.x,
    y: 0,
    width: l.w,
    height: 26,
    name: l.party.name
  }));
  let lives = lanes.map(l => ({
    TAG: "Life",
    x: l.centre,
    top: 26,
    bottom: bottom
  }));
  let messages = [];
  let states = [];
  let reaches = [];
  steps.forEach((step, index) => {
    let y = 26 + 24 + index * 32;
    if (step.TAG === "Said") {
      let label = step.label;
      let from = lane(step.from).centre;
      let to = lane(step.to).centre;
      messages.push({
        TAG: "Message",
        from: from,
        to: to,
        y: y,
        refused: step.refused,
        label: label === "" ? undefined : ({
            x: Math.round((from + to) / 2),
            y: y - 5,
            text: label
          })
      });
      return;
    }
    let label$1 = step.label;
    let l = lane(step.on);
    let w = Math.ceil(width(label$1, 11) + 12 * 2);
    let x = l.centre - w / 2;
    reaches.push(x);
    reaches.push(x + w);
    states.push({
      TAG: "State",
      x: x,
      y: y - 20 / 2,
      width: w,
      height: 20,
      text: label$1
    });
  });
  let right = Stdlib_Array.reduce(lanes, 0, (most, l) => Math.max(most, l.x + l.w));
  let left = Math.min(...Belt_Array.concatMany([
    [0],
    reaches
  ]));
  let w = Math.max(...Belt_Array.concatMany([
    [right],
    reaches
  ])) - left;
  let keys;
  if (match[2]) {
    let used = unique(parties.map(p => p.kind)).filter(kind => kind !== defaultKind);
    let lines = unique(steps.map(step => {
      if (step.TAG === "Said") {
        if (step.refused) {
          return "refused";
        } else {
          return "message";
        }
      } else {
        return "state";
      }
    }));
    keys = Belt_Array.concatMany([
      used.map(kind => ({
        kind: kind,
        text: Stdlib_Option.getOr(kinds[kind], kind),
        move: false
      })),
      lines.map(kind => ({
        kind: kind,
        text: Stdlib_Option.mapOr(lineKeys.find(param => param[0] === kind), "", prim => prim[1]),
        move: false
      }))
    ]);
  } else {
    keys = [];
  }
  return {
    ops: Belt_Array.concatMany([
      [{
          TAG: "Frame",
          _0: {
            left: left - 10,
            top: - 10,
            width: w + 10 * 2,
            height: bottom + 10 * 2
          }
        }],
      heads,
      lives,
      messages,
      states
    ]),
    caption: caption,
    keys: keys
  };
}

function n(prim0, prim1) {
  return prim0.toString(prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
}

function tone(kind) {
  if (kind === defaultKind) {
    return "";
  } else {
    return ` style="--tone: var(--tone-` + kind + `, var(--blocks-ink))"`;
  }
}

let tips = `<defs><marker id="sequence-tip" viewBox="0 0 14 10" refX="13" refY="5" markerWidth="14" markerHeight="10" markerUnits="userSpaceOnUse" orient="auto"><path class="sequence__tip" d="M 0 0 L 14 5 L 0 10 L 3.8 5 z" /></marker><marker id="sequence-cross" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="10" markerHeight="10" markerUnits="userSpaceOnUse" orient="auto"><path class="sequence__cross" d="M 1.5 1.5 L 8.5 8.5 M 8.5 1.5 L 1.5 8.5" /></marker></defs>`;

function render(drawing) {
  let pick = f => Stdlib_Array.filterMap(drawing.ops, f).join("");
  let frame = Stdlib_Option.getOrThrow(Stdlib_Array.findMap(drawing.ops, op => {
    if (op.TAG === "Frame") {
      return op._0;
    }
  }), undefined);
  let lives = pick(op => {
    if (op.TAG !== "Life") {
      return;
    }
    let x = op.x;
    return `<line class="sequence__life" x1="` + x.toString() + `" y1="` + op.top.toString() + `" x2="` + x.toString() + `" y2="` + op.bottom.toString() + `" />`;
  });
  let heads = pick(op => {
    if (op.TAG !== "Head") {
      return;
    }
    let height = op.height;
    let width = op.width;
    let y = op.y;
    let x = op.x;
    let kind = op.kind;
    return `<g class="sequence__head sequence__head--` + kind + `"` + tone(kind) + `><rect x="` + x.toString() + `" y="` + y.toString() + `" width="` + width.toString() + `" height="` + height.toString() + `" rx="7" /><text x="` + (x + width / 2).toString() + `" y="` + (y + height / 2 + 4).toString() + `" text-anchor="middle">` + Html.escape(op.name) + `</text></g>`;
  });
  let lines = pick(op => {
    if (op.TAG !== "Message") {
      return;
    }
    let refused = op.refused;
    let y = op.y;
    let text = Stdlib_Option.mapOr(op.label, "", l => l.text);
    return `<path class="sequence__message` + (
      refused ? " sequence__message--refused" : ""
    ) + `" marker-end="url(#` + (
      refused ? "sequence-cross" : "sequence-tip"
    ) + `)" d="M ` + op.from.toString() + ` ` + y.toString() + ` L ` + op.to.toString() + ` ` + y.toString() + `" data-step="` + Html.escape(text) + `" />`;
  });
  let boxes = pick(op => {
    if (op.TAG !== "State") {
      return;
    }
    let height = op.height;
    let width = op.width;
    let y = op.y;
    let x = op.x;
    return `<g class="sequence__state"><rect x="` + x.toString() + `" y="` + y.toString() + `" width="` + width.toString() + `" height="` + height.toString() + `" rx="6" /><text x="` + (x + width / 2).toString() + `" y="` + (y + height / 2 + 4).toString() + `" text-anchor="middle">` + Html.escape(op.text) + `</text></g>`;
  });
  let notes = pick(op => {
    if (op.TAG !== "Message") {
      return;
    }
    let match = op.label;
    if (match !== undefined) {
      return `<text class="sequence__label` + (
        op.refused ? " sequence__label--refused" : ""
      ) + `" text-anchor="middle" x="` + match.x.toString() + `" y="` + match.y.toString() + `">` + Html.escape(match.text) + `</text>`;
    }
  });
  let label = Stdlib_Option.getOr(drawing.caption, "A sequence");
  let title = Stdlib_Option.mapOr(drawing.caption, "", c => `<span class="sequence__title">` + Html.escape(c) + `</span>`);
  let keyed = Primitive_object.equal(drawing.keys, []) ? "" : `<span class="sequence__keys">` + drawing.keys.map(param => {
      let kind = param.kind;
      return `<span class="sequence__key sequence__key--` + kind + `"` + (
        lineKeys.some(param => param[0] === kind) ? "" : tone(kind)
      ) + `>` + Html.escape(param.text) + `</span>`;
    }).join("") + `</span>`;
  let under = title + keyed === "" ? "" : `<figcaption class="sequence__caption">` + title + keyed + `</figcaption>`;
  return `<figure class="sequence"><svg class="sequence__svg" viewBox="` + frame.left.toString() + ` ` + frame.top.toString() + ` ` + frame.width.toString() + ` ` + frame.height.toString() + `" width="` + frame.width.toString() + `" height="` + frame.height.toString() + `" role="img" aria-label="` + Html.escape(label) + `">` + tips + lives + heads + lines + boxes + notes + `</svg>` + under + `</figure>`;
}

let fail = Html.fail;

let headHeight = 26;

let laneLeast = 84;

let pad = 12;

let stepHeight = 32;

let gapLeast = 64;

let top = 24;

let margin = 10;

let stateHeight = 20;

let labelUp = 5;

let escape = Html.escape;

export {
  fail,
  headHeight,
  laneLeast,
  pad,
  stepHeight,
  gapLeast,
  top,
  margin,
  stateHeight,
  labelUp,
  chars,
  narrow,
  wide,
  width,
  defaultKind,
  lineKeys,
  partyCell,
  moveLine,
  stateLine,
  directiveLine,
  space,
  capture,
  readText,
  place,
  unique,
  read,
  n,
  tone,
  escape,
  tips,
  render,
}
/* narrow Not a pure module */
