// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Html from "./Html.res.mjs";
import * as Sequence from "./Sequence.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Float from "@rescript/runtime/lib/es6/Stdlib_Float.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

function normal(side) {
  switch (side) {
    case "Right" :
      return {
        x: 1,
        y: 0
      };
    case "Left" :
      return {
        x: -1,
        y: 0
      };
    case "Top" :
      return {
        x: 0,
        y: -1
      };
    case "Bottom" :
      return {
        x: 0,
        y: 1
      };
  }
}

let defaultKind = "step";

let cellLine = new RegExp("^[\\p{L}\\p{N}_.\\-]+(?::[\\p{L}]+)?$", "u");

let moveLine = new RegExp("^ *(\\S+) +-> +(\\S+)(?: +(.*))?$");

let placedLabel = new RegExp("^(.*?)\\s*\\{(?:([01](?:\\.\\d+)?))?\\s*(right)?\\s*([\\p{L}]+)?\\}$", "u");

let space = new RegExp("\\s+");

function readText(text, keys) {
  let rows = [];
  let moves = [];
  let legend = {
    contents: false
  };
  let past = {
    contents: false
  };
  text.split("\n").forEach((raw, index) => {
    let line = raw.trimEnd();
    let at = `line ` + (index + 1 | 0).toString();
    if (line.trim() === "") {
      if (rows.length !== 0) {
        past.contents = true;
        return;
      } else {
        return;
      }
    }
    if (line.trim().startsWith("#")) {
      return;
    }
    let d = Sequence.directiveLine.exec(line.trim());
    if (d == null) {
      if (past.contents) {
        let m = moveLine.exec(line);
        if (m == null) {
          return Html.fail(`states: cannot read the move at ` + at);
        }
        let said = Stdlib_Option.getOr(Sequence.capture(m, 2), "").trim();
        let placed = placedLabel.exec(said);
        let placed$1 = (placed == null) ? undefined : Primitive_option.some(placed);
        let kind = Stdlib_Option.flatMap(placed$1, p => Sequence.capture(p, 3));
        Stdlib_Option.forEach(kind, kind => {
          if (Stdlib_Option.isNone(keys[kind])) {
            return Html.fail(`states: no kind called ` + kind + `, ` + at);
          }
        });
        moves.push({
          from: Stdlib_Option.getOr(Sequence.capture(m, 0), ""),
          to: Stdlib_Option.getOr(Sequence.capture(m, 1), ""),
          label: Stdlib_Option.getOr(Stdlib_Option.flatMap(placed$1, p => Sequence.capture(p, 0)), said),
          at: Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_Option.flatMap(placed$1, p => Sequence.capture(p, 1)), Stdlib_Float.fromString), 0.5),
          right: Stdlib_Option.isSome(Stdlib_Option.flatMap(placed$1, p => Sequence.capture(p, 2))),
          kind: kind
        });
        return;
      }
      let cells = line.trim().split(space).map(c => Stdlib_Option.getOr(c, ""));
      if (!cells.every(c => c === "." ? true : cellLine.test(c))) {
        Html.fail(`states: cannot read the grid at ` + at);
      }
      rows.push(cells.map(c => {
        if (c === ".") {
          return;
        }
        let match = c.split(":");
        let match$1;
        if (match.length !== 2) {
          match$1 = [
            c,
            defaultKind
          ];
        } else {
          let name = match[0];
          let kind = match[1];
          match$1 = [
            name,
            kind
          ];
        }
        let kind$1 = match$1[1];
        if (Stdlib_Option.isNone(keys[kind$1])) {
          Html.fail(`states: no kind called ` + kind$1 + `, ` + at);
        }
        return {
          name: match$1[0],
          kind: kind$1
        };
      }));
      return;
    }
    let name = Stdlib_Option.getOr(Sequence.capture(d, 0), "");
    if (name !== "legend") {
      Html.fail(`states: no directive {` + name + `}, ` + at);
    }
    legend.contents = true;
  });
  if (rows.length === 0) {
    Html.fail("states: the grid is empty");
  }
  let placed = Stdlib_Array.filterMap(rows.flat(), c => c).map(c => c.name);
  moves.forEach(move => {
    [
      move.from,
      move.to
    ].forEach(end => {
      if (!placed.includes(end)) {
        return Html.fail(`states: no box called ` + end);
      }
    });
  });
  return [
    rows,
    moves,
    legend.contents
  ];
}

function place(rows) {
  let columns = Stdlib_Array.reduce(rows, 0, (most, row) => Math.max(most, row.length));
  let widths = Stdlib_Array.fromInitializer(columns, column => {
    let names = Stdlib_Array.filterMap(rows, row => Stdlib_Option.flatMap(row[column], c => c));
    if (Primitive_object.equal(names, [])) {
      return 46;
    } else {
      return Math.ceil(Math.max(...names.map(c => Sequence.width(c.name, 13) + 13 * 2)));
    }
  });
  let lefts = [];
  let x = {
    contents: 0
  };
  widths.forEach(w => {
    lefts.push(x.contents);
    x.contents = x.contents + w + 46;
  });
  let boxes = [];
  rows.forEach((row, line) => {
    row.forEach((cell, column) => Stdlib_Option.forEach(cell, cell => {
      let x = lefts[column];
      let y = line * (30 + 84);
      let w = widths[column];
      boxes.push({
        name: cell.name,
        kind: cell.kind,
        row: line,
        column: column,
        x: x,
        y: y,
        w: w,
        middle: y + 30 / 2,
        centre: x + w / 2
      });
    }));
  });
  return [
    boxes,
    Stdlib_Array.reduce(boxes, 0, (most, b) => Math.max(most, b.x + b.w))
  ];
}

function along(t, p0, p1, p2, p3) {
  let u = 1 - t;
  return u * u * u * p0 + 3 * u * u * t * p1 + 3 * u * t * t * p2 + t * t * t * p3;
}

function shape(move, boxes) {
  let get = name => Stdlib_Option.getOrThrow(boxes.findLast(b => b.name === name), undefined);
  let from = get(move.from);
  let to = get(move.to);
  let match;
  if (from.row === to.row) {
    let low = Math.min(from.column, to.column);
    let high = Math.max(from.column, to.column);
    let blocked = boxes.some(b => {
      if (b.row === from.row && b.column > low) {
        return b.column < high;
      } else {
        return false;
      }
    });
    match = blocked ? [
        "Top",
        "Top"
      ] : (
        to.column > from.column ? [
            "Right",
            "Left"
          ] : [
            "Left",
            "Right"
          ]
      );
  } else {
    match = to.row > from.row ? [
        "Bottom",
        "Top"
      ] : [
        "Top",
        "Bottom"
      ];
  }
  return {
    move: move,
    from: from,
    to: to,
    fromSide: match[0],
    toSide: match[1],
    tail: undefined,
    head: undefined
  };
}

function sign(x) {
  if (x > 0) {
    return 1;
  } else if (x < 0) {
    return -1;
  } else {
    return 0;
  }
}

function orElse(first, second) {
  if (first !== 0) {
    return first;
  } else {
    return second;
  }
}

function anchor(lines) {
  let sides = [];
  let put = (box, side, line, far) => {
    let match = sides.find(param => {
      if (param[0].name === box.name) {
        return param[1] === side;
      } else {
        return false;
      }
    });
    if (match !== undefined) {
      match[2].push([
        line,
        far
      ]);
    } else {
      sides.push([
        box,
        side,
        [[
            line,
            far
          ]]
      ]);
    }
  };
  lines.forEach(line => {
    put(line.from, line.fromSide, line, line.to);
    put(line.to, line.toSide, line, line.from);
  });
  sides.forEach(param => {
    let ends = param[2];
    let side = param[1];
    let box = param[0];
    let across = side === "Top" || side === "Bottom";
    let reach = far => Math.abs(far.middle - box.middle) * sign(orElse(far.centre - box.centre, 1));
    ends.sort((param, param$1) => {
      let other = param$1[1];
      let one = param[1];
      if (across) {
        return orElse(one.centre - other.centre, reach(other) - reach(one));
      } else {
        return one.middle - other.middle;
      }
    });
    let run = across ? box.w : 30;
    let start = across ? box.x : box.y;
    let count = ends.length + 1 | 0;
    ends.forEach((param, index) => {
      let line = param[0];
      let at = start + run * (index + 1 | 0) / count;
      let point = across ? ({
          x: at,
          y: side === "Top" ? box.y : box.y + 30
        }) : ({
          x: side === "Left" ? box.x : box.x + box.w,
          y: at
        });
      if (line.from.name === box.name && line.fromSide === side && Stdlib_Option.isNone(line.tail)) {
        line.tail = point;
      } else {
        line.head = point;
      }
    });
  });
  return lines;
}

function draw(line, paired) {
  let tail = Stdlib_Option.getOrThrow(line.tail, undefined);
  let head = Stdlib_Option.getOrThrow(line.head, undefined);
  let out = normal(line.fromSide);
  let into = normal(line.toSide);
  let span = Math.hypot(head.x - tail.x, head.y - tail.y);
  let pull = Math.min(Math.max(span * 0.45, 34), 96);
  let one_x = tail.x + out.x * pull;
  let one_y = tail.y + out.y * pull;
  let other_x = head.x + into.x * pull;
  let other_y = head.y + into.y * pull;
  let at = t => ({
    x: along(t, tail.x, one_x, other_x, head.x),
    y: along(t, tail.y, one_y, other_y, head.y)
  });
  let where = line.move.at;
  let middle = at(where);
  let ahead = at(Math.min(where + 0.04, 1));
  let behind = at(Math.max(where - 0.04, 0));
  let run = orElse(Math.hypot(ahead.x - behind.x, ahead.y - behind.y), 1);
  let left_x = (ahead.y - behind.y) / run;
  let left_y = (behind.x - ahead.x) / run;
  let left = {
    x: left_x,
    y: left_y
  };
  let away_x = middle.x - (line.from.centre + line.to.centre) / 2;
  let away_y = middle.y - (line.from.middle + line.to.middle) / 2;
  let outward = left_x * away_x + left_y * away_y >= 0;
  let flipped = line.move.right || paired && !outward;
  let side = flipped ? ({
      x: - left_x,
      y: - left_y
    }) : left;
  let x = middle.x + side.x * 11;
  let y = middle.y + side.y * 11 + (
    side.y < -0.5 ? -1 : (
        side.y > 0.5 ? 9 : 4
      )
  );
  return {
    move: line.move,
    points: [
      tail.x,
      tail.y,
      one_x,
      one_y,
      other_x,
      other_y,
      head.x,
      head.y
    ],
    x: x,
    y: y,
    anchor: side.x > 0.5 ? "start" : (
        side.x < -0.5 ? "end" : "middle"
      ),
    ridden: [
      0,
      0.25,
      0.5,
      0.75,
      1
    ].map(at)
  };
}

function pairKey(one, other) {
  return [
    one,
    other
  ].toSorted(Primitive_string.compare).join(" ");
}

function read(text, caption, kinds) {
  let keys = Object.fromEntries(Belt_Array.concatMany([
    [[
        defaultKind,
        "a step"
      ]],
    Object.entries(kinds)
  ]));
  let match = readText(text, keys);
  let moves = match[1];
  let match$1 = place(match[0]);
  let boxes = match$1[0];
  let lines = anchor(moves.map(move => shape(move, boxes)));
  let pairs = {};
  lines.forEach(line => {
    let key = pairKey(line.from.name, line.to.name);
    pairs[key] = Stdlib_Option.getOr(pairs[key], 0) + 1 | 0;
  });
  let drawn = lines.map(line => draw(line, Stdlib_Option.getOr(pairs[pairKey(line.from.name, line.to.name)], 0) > 1));
  let ridden = drawn.flatMap(d => d.ridden.map(p => p.y));
  let top = Math.min(...Belt_Array.concatMany([
    boxes.map(b => b.y),
    ridden,
    drawn.map(d => d.y - 12)
  ]));
  let bottom = Math.max(...Belt_Array.concatMany([
    boxes.map(b => b.y + 30),
    ridden,
    drawn.map(d => d.y + 6)
  ]));
  let reaches = drawn.flatMap(d => {
    if (d.move.label === "") {
      return [];
    }
    let run = Sequence.width(d.move.label, 11);
    let left = d.anchor === "start" ? d.x : (
        d.anchor === "end" ? d.x - run : d.x - run / 2
      );
    return [
      left,
      left + run
    ];
  });
  let left = Math.min(...Belt_Array.concatMany([
    [0],
    reaches
  ]));
  let w = Math.max(...Belt_Array.concatMany([
    [match$1[1]],
    reaches
  ])) - left;
  let used = Sequence.unique(boxes.map(b => b.kind));
  let marked = Sequence.unique(Stdlib_Array.filterMap(moves, m => m.kind));
  let key = (kind, move) => ({
    kind: kind,
    text: Stdlib_Option.getOr(keys[kind], kind),
    move: move
  });
  return {
    ops: Belt_Array.concatMany([
      [{
          TAG: "Frame",
          _0: {
            left: left - 10,
            top: top - 10,
            width: w + 10 * 2,
            height: bottom - top + 10 * 2
          }
        }],
      boxes.map(b => ({
        TAG: "Box",
        kind: b.kind,
        x: b.x,
        y: b.y,
        width: b.w,
        height: 30,
        name: b.name
      })),
      drawn.map(d => ({
        TAG: "Move",
        kind: d.move.kind,
        points: d.points,
        label: d.move.label === "" ? undefined : [
            {
              x: Math.round(d.x),
              y: Math.round(d.y),
              text: d.move.label
            },
            d.anchor
          ]
      }))
    ]),
    caption: caption,
    keys: match[2] ? Belt_Array.concatMany([
        used.map(kind => key(kind, false)),
        marked.map(kind => key(kind, true))
      ]) : []
  };
}

function n(prim0, prim1) {
  return prim0.toString(prim1 !== undefined ? Primitive_option.valFromOption(prim1) : undefined);
}

function tone(kind) {
  if (kind === defaultKind) {
    return "";
  } else {
    return ` style="--tone: var(--tone-` + kind + `, var(--blocks-ink))"`;
  }
}

function marker(kind) {
  return `<marker id="states-tip` + Stdlib_Option.mapOr(kind, "", k => `-` + k) + `"` + Stdlib_Option.mapOr(kind, "", tone) + ` viewBox="0 0 14 10" refX="13" refY="5" markerWidth="14" markerHeight="10" markerUnits="userSpaceOnUse" orient="auto"><path class="states__tip" d="M 0 0 L 14 5 L 0 10 L 3.8 5 z" /></marker>`;
}

function render(drawing) {
  let pick = f => Stdlib_Array.filterMap(drawing.ops, f).join("");
  let frame = Stdlib_Option.getOrThrow(Stdlib_Array.findMap(drawing.ops, op => {
    switch (op.TAG) {
      case "Frame" :
        return op._0;
      case "Box" :
      case "Move" :
        return;
    }
  }), undefined);
  let paths = pick(op => {
    switch (op.TAG) {
      case "Frame" :
      case "Box" :
        return;
      case "Move" :
        let match = op.points;
        if (match.length !== 8) {
          return;
        }
        let kind = op.kind;
        let x0 = match[0];
        let y0 = match[1];
        let x1 = match[2];
        let y1 = match[3];
        let x2 = match[4];
        let y2 = match[5];
        let x3 = match[6];
        let y3 = match[7];
        let text = Stdlib_Option.mapOr(op.label, "", param => param[0].text);
        let modifier = Stdlib_Option.mapOr(kind, "", k => ` states__move--` + k);
        let colour = Stdlib_Option.mapOr(kind, "", tone);
        let tip = Stdlib_Option.mapOr(kind, "states-tip", k => `states-tip-` + k);
        return `<path class="states__move` + modifier + `"` + colour + ` marker-end="url(#` + tip + `)" d="M ` + x0.toString() + ` ` + y0.toString() + ` C ` + x1.toString() + ` ` + y1.toString() + `, ` + x2.toString() + ` ` + y2.toString() + `, ` + x3.toString() + ` ` + y3.toString() + `" data-move="` + Html.escape(text) + `" />`;
    }
  });
  let shapes = pick(op => {
    switch (op.TAG) {
      case "Box" :
        let height = op.height;
        let width = op.width;
        let y = op.y;
        let x = op.x;
        let kind = op.kind;
        return `<g class="states__box states__box--` + kind + `"` + tone(kind) + `><rect x="` + x.toString() + `" y="` + y.toString() + `" width="` + width.toString() + `" height="` + height.toString() + `" rx="7" /><text x="` + (x + width / 2).toString() + `" y="` + (y + height / 2 + 4).toString() + `" text-anchor="middle">` + Html.escape(op.name) + `</text></g>`;
      case "Frame" :
      case "Move" :
        return;
    }
  });
  let notes = pick(op => {
    switch (op.TAG) {
      case "Frame" :
      case "Box" :
        return;
      case "Move" :
        let match = op.label;
        if (match === undefined) {
          return;
        }
        let match$1 = match[0];
        return `<text class="states__label"` + Stdlib_Option.mapOr(op.kind, "", tone) + ` text-anchor="` + match[1] + `" x="` + match$1.x.toString() + `" y="` + match$1.y.toString() + `">` + Html.escape(match$1.text) + `</text>`;
    }
  });
  let label = Stdlib_Option.getOr(drawing.caption, "A state machine");
  let title = Stdlib_Option.mapOr(drawing.caption, "", c => `<span class="states__title">` + Html.escape(c) + `</span>`);
  let keyed = Primitive_object.equal(drawing.keys, []) ? "" : `<span class="states__keys">` + drawing.keys.map(param => {
      let kind = param.kind;
      return `<span class="states__key states__key--` + kind + (
        param.move ? " states__key--move" : ""
      ) + `"` + tone(kind) + `>` + Html.escape(param.text) + `</span>`;
    }).join("") + `</span>`;
  let under = title + keyed === "" ? "" : `<figcaption class="states__caption">` + title + keyed + `</figcaption>`;
  let kinds = Sequence.unique(Stdlib_Array.filterMap(drawing.ops, op => {
    switch (op.TAG) {
      case "Frame" :
      case "Box" :
        return;
      case "Move" :
        return op.kind;
    }
  }));
  let tips = `<defs>` + Belt_Array.concatMany([
    [undefined],
    kinds.map(k => k)
  ]).map(marker).join("") + `</defs>`;
  return `<figure class="states"><svg class="states__svg" viewBox="` + frame.left.toString() + ` ` + frame.top.toString() + ` ` + frame.width.toString() + ` ` + frame.height.toString() + `" width="` + frame.width.toString() + `" height="` + frame.height.toString() + `" role="img" aria-label="` + Html.escape(label) + `">` + tips + paths + shapes + notes + `</svg>` + under + `</figure>`;
}

let fail = Html.fail;

let width = Sequence.width;

let capture = Sequence.capture;

let boxHeight = 30;

let pad = 13;

let gapX = 46;

let lane = 46;

let gapY = 84;

let margin = 10;

let pull = 0.45;

let pullLeast = 34;

let pullMost = 96;

let labelOff = 11;

let escape = Html.escape;

export {
  fail,
  width,
  capture,
  boxHeight,
  pad,
  gapX,
  lane,
  gapY,
  margin,
  pull,
  pullLeast,
  pullMost,
  labelOff,
  normal,
  defaultKind,
  cellLine,
  moveLine,
  placedLabel,
  space,
  readText,
  place,
  along,
  shape,
  sign,
  orElse,
  anchor,
  draw,
  pairKey,
  read,
  n,
  tone,
  escape,
  marker,
  render,
}
/* cellLine Not a pure module */
