// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function quote(text) {
  return `"` + text.replaceAll("\"", "\\\"") + `"`;
}

function num(v) {
  return (Math.round(v * 100) / 100).toString();
}

function nums(values) {
  return values.map(num).join(" ");
}

function field(name, value) {
  return Stdlib_Option.mapOr(value, "", v => ` ` + name + ` ` + quote(v));
}

function flag(name, on) {
  if (on) {
    return ` ` + name;
  } else {
    return "";
  }
}

function markdown(text, pad) {
  return text.split("\n").map(line => {
    if (line === "") {
      return pad + `|`;
    } else {
      return pad + `| ` + line;
    }
  });
}

function keys(drawing, pad) {
  return Belt_Array.concatMany([
    Stdlib_Option.mapOr(drawing.caption, [], c => [pad + `caption ` + quote(c)]),
    drawing.keys.map(k => pad + `key ` + k.kind + ` ` + quote(k.text) + flag("move", k.move))
  ]);
}

function sequenceOp(op, pad) {
  switch (op.TAG) {
    case "Frame" :
      let match = op._0;
      return [pad + `frame ` + nums([
          match.left,
          match.top,
          match.width,
          match.height
        ])];
    case "Head" :
      return [pad + `head ` + op.kind + ` ` + nums([
          op.x,
          op.y,
          op.width,
          op.height
        ]) + ` ` + quote(op.name)];
    case "Life" :
      return [pad + `life ` + nums([
          op.x,
          op.top,
          op.bottom
        ])];
    case "Message" :
      return Belt_Array.concatMany([
        [pad + (
            op.refused ? "refused" : "message"
          ) + ` ` + nums([
            op.from,
            op.to,
            op.y
          ])],
        Stdlib_Option.mapOr(op.label, [], l => [pad + `  label ` + nums([
            l.x,
            l.y
          ]) + ` ` + quote(l.text)])
      ]);
    case "State" :
      return [pad + `state ` + nums([
          op.x,
          op.y,
          op.width,
          op.height
        ]) + ` ` + quote(op.text)];
  }
}

function statesOp(op, pad) {
  switch (op.TAG) {
    case "Frame" :
      let match = op._0;
      return [pad + `frame ` + nums([
          match.left,
          match.top,
          match.width,
          match.height
        ])];
    case "Box" :
      return [pad + `box ` + op.kind + ` ` + nums([
          op.x,
          op.y,
          op.width,
          op.height
        ]) + ` ` + quote(op.name)];
    case "Move" :
      return Belt_Array.concatMany([
        [pad + `move` + Stdlib_Option.mapOr(op.kind, "", k => ` ` + k) + ` ` + nums(op.points)],
        Stdlib_Option.mapOr(op.label, [], param => {
          let l = param[0];
          return [pad + `  label ` + nums([
              l.x,
              l.y
            ]) + ` ` + param[1] + ` ` + quote(l.text)];
        })
      ]);
  }
}

function widget(w, pad) {
  switch (w.TAG) {
    case "Text" :
      return markdown(w._0, pad);
    case "Actions" :
      return Belt_Array.concatMany([
        [pad + `actions`],
        w._0.map(b => pad + `  button ` + quote(b.text) + flag("primary", b.primary) + flag("clicked", b.clicked))
      ]);
    case "Options" :
      return Belt_Array.concatMany([
        [pad + `options`],
        w._0.map(c => pad + `  ` + (
          c.radio ? "radio" : "check"
        ) + ` ` + quote(c.text) + flag("on", c.on))
      ]);
    case "Field" :
      return [pad + `field ` + quote(w._0)];
  }
}

function lines(node, pad) {
  let inner = pad + `  `;
  let children = nodes => nodes.flatMap(n => lines(n, inner));
  switch (node.TAG) {
    case "Markdown" :
      return markdown(node._0, pad);
    case "Callout" :
      return Belt_Array.concatMany([
        [pad + `callout ` + node.name + ` ` + quote(node.label)],
        children(node.children)
      ]);
    case "Quote" :
      return Belt_Array.concatMany([
        [pad + `quote` + field("author", node.author) + field("date", node.date)],
        children(node.children)
      ]);
    case "Flow" :
      return Belt_Array.concatMany([
        [pad + `flow ` + quote(node.label)],
        node.columns.flatMap(column => Belt_Array.concatMany([
          [inner + `column` + Stdlib_Option.mapOr(column.title, "", t => ` ` + quote(t))],
          column.steps.flatMap(step => Belt_Array.concatMany([
            [inner + `  step ` + quote(step.text)],
            step.details.map(d => inner + `    detail ` + quote(d))
          ]))
        ]))
      ]);
    case "Dialog" :
      return Belt_Array.concatMany([
        [pad + `ui-dialog` + Stdlib_Option.mapOr(node.owner, "", param => ` owner ` + param[0] + ` ` + quote(param[1])) + field("title", node.title)],
        node.widgets.flatMap(w => widget(w, inner))
      ]);
    case "Screens" :
      return Belt_Array.concatMany([
        [pad + `ui-flow` + field("caption", node.caption)],
        children(node.children)
      ]);
    case "Sequence" :
      let drawing = node._0;
      return Belt_Array.concatMany([
        [pad + `sequence`],
        drawing.ops.flatMap(op => sequenceOp(op, inner)),
        keys(drawing, inner)
      ]);
    case "States" :
      let drawing$1 = node._0;
      return Belt_Array.concatMany([
        [pad + `states`],
        drawing$1.ops.flatMap(op => statesOp(op, inner)),
        keys(drawing$1, inner)
      ]);
    case "Extra" :
      return Belt_Array.concatMany([
        [pad + `extra ` + node.name + ` ` + quote(node.info)],
        markdown(node.body, inner)
      ]);
  }
}

function write(nodes) {
  return nodes.flatMap(n => lines(n, "")).join("\n");
}

export {
  quote,
  num,
  nums,
  field,
  flag,
  markdown,
  keys,
  sequenceOp,
  statesOp,
  widget,
  lines,
  write,
}
/* No side effect */
