// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dev from "./Dev.res.mjs";
import * as Tilia from "tilia/src/Tilia.res.mjs";
import * as Schema from "./Schema.res.mjs";
import * as Marked from "marked";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

let defaults = Object.fromEntries([
  [
    "md",
    text => Marked.marked.parse(text, {
      async: false
    })
  ],
  [
    "none",
    text => text
  ]
]);

let reference = new RegExp("\\{\\{\\s*(`?)([A-Za-z_][A-Za-z0-9_.-]*)\\1\\s*\\}\\}", "g");

let backtick = new RegExp("`", "g");

let stack = {
  contents: []
};

let cycle = {
  contents: undefined
};

let rawSite = ((at, fn) => {
  try { return fn() } catch (e) {
    if (e && e.message && !e.minidocSited) {
      e.minidocSited = true
      e.message = e.message.startsWith("Variable cycle:")
        ? "Variable cycle in " + at + ":" + e.message.slice(15)
        : e.message + " in " + at
    }
    throw e
  }
});

let rawBoxed = ((stack, inline, fn) => {
  if (!inline) return fn()
  const active = stack.contents
  try { return fn() } catch (e) {
    stack.contents = active
    const message = String((e && e.message) || e)
    console.error("minidoc: " + message)
    const text = message.replace(/&/g, "&amp;").replace(/</g, "&lt;")
    return '<div class="minidoc-error" style="border:1px solid #c00;background:rgba(255,0,0,.04);padding:.5em .75em;font-family:monospace;white-space:pre-wrap;">' + text + '</div>'
  }
});

function lined(template, offset) {
  if (template.includes("\n")) {
    return ` at line ` + template.slice(0, offset).split("\n").length.toString();
  } else {
    return "";
  }
}

function unpad(text, pad) {
  let go = _i => {
    while (true) {
      let i = _i;
      if (!(i < pad && text.charAt(i) === "\n")) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  return text.slice(go(0));
}

function data(front) {
  return Stdlib_Dict.mapValues(front, d => {
    if (d.TAG === "One") {
      return {
        TAG: "T",
        _0: d._0
      };
    } else {
      return {
        TAG: "L",
        _0: d._0
      };
    }
  });
}

function naming(c) {
  let name = c.path.slice(c.path.lastIndexOf("/") + 1 | 0);
  let dot = name.lastIndexOf(".");
  let stem = dot > 0 ? name.slice(0, dot) : name;
  return Object.fromEntries([
    [
      "file.name",
      {
        TAG: "V",
        _0: {
          TAG: "One",
          _0: name
        }
      }
    ],
    [
      "file.stem",
      {
        TAG: "V",
        _0: {
          TAG: "One",
          _0: stem
        }
      }
    ]
  ]);
}

function make(inline, lvars) {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      lvars: lvars,
      vars: Stdlib_Dict.mapValues(lvars, lv => derived(self => $$eval(lv, self))),
      get: derived(self => (name => self.vars[name])),
      inline: inline
    };
  });
}

function sub(self, extra) {
  return make(self.inline, Object.assign(Object.assign({}, self.lvars), extra));
}

function $$eval(lv, self) {
  switch (lv.TAG) {
    case "T" :
      return {
        TAG: "One",
        _0: render(lv._0, self.get)
      };
    case "L" :
      return {
        TAG: "Many",
        _0: lv._0.map(__x => render(__x, self.get))
      };
    case "V" :
      return lv._0;
    case "F" :
      let c = lv._0;
      return {
        TAG: "One",
        _0: rawBoxed(stack, self.inline, () => rawSite(c.at, () => unpad(c.transform(render(c.body, sub(self, data(c.front)).get)), c.pad)))
      };
    case "D" :
      let at = lv._2;
      let each = lv._1;
      let items = lv._0;
      return {
        TAG: "One",
        _0: rawSite(at, () => items.map(c => rawBoxed(stack, self.inline, () => rawSite(at, () => {
          let own = data(c.front);
          let parent = naming(c);
          let front = sub(self, Object.assign(Object.assign({}, parent), own));
          let body = unpad(c.transform(rawSite(c.at, () => render(c.body, front.get))), c.pad);
          return render(each, sub(front, Object.fromEntries([[
              "body",
              {
                TAG: "V",
                _0: {
                  TAG: "One",
                  _0: body
                }
              }
            ]])).get);
        }))).join("\n"))
      };
    case "R" :
      let at$1 = lv._1;
      let l = lv._0;
      return {
        TAG: "One",
        _0: rawBoxed(stack, self.inline, () => rawSite(at$1, () => {
          let match = self.get(l.list);
          if (match === undefined) {
            return Schema.fail(`Undefined variable {{` + l.list + `}}`);
          }
          if (match.TAG === "One") {
            return Schema.fail(`"` + l.list + `" must resolve to a scalar list`);
          }
          let items = match._0;
          if (items.length === 0) {
            return "";
          }
          let one = (name, value, template) => render(template, sub(self, Object.fromEntries([[
              name,
              {
                TAG: "V",
                _0: {
                  TAG: "One",
                  _0: value
                }
              }
            ]])).get);
          let body = items.map(item => one("item", item, l.each)).join(Stdlib_Option.getOr(l.join, ""));
          let template = l.template;
          if (template !== undefined) {
            return one("body", body, template);
          } else {
            return body;
          }
        }))
      };
    case "P" :
      let at$2 = lv._2;
      let transform = lv._1;
      let value = lv._0;
      return {
        TAG: "One",
        _0: rawBoxed(stack, self.inline, () => rawSite(at$2, () => transform(render(value, self.get))))
      };
  }
}

function render(template, get) {
  return template.replace(reference, (ref, quote, name, offset, input) => {
    if (quote !== "") {
      return ref.replace(backtick, "");
    }
    let active = stack.contents;
    if (active.includes(name)) {
      let from = active.indexOf(name);
      let path = cycle.contents;
      let path$1 = path !== undefined ? path : Belt_Array.concatMany([
          active.slice(from),
          [name]
        ]).join(" -> ");
      cycle.contents = path$1;
      Schema.fail(`Variable cycle: ` + path$1);
    }
    stack.contents = Belt_Array.concatMany([
      active,
      [name]
    ]);
    let match = get(name);
    let out = match !== undefined ? (
        match.TAG === "One" ? match._0 : match._0.join("")
      ) : Schema.fail(`Undefined variable ` + ref + lined(input, offset));
    stack.contents = active;
    return out;
  });
}

function top(at, fn) {
  stack.contents = [];
  cycle.contents = undefined;
  return rawSite(at, fn);
}

let special = new RegExp("[.*+?^${}()|[\\]\\\\]", "g");

let slashes = new RegExp("\\\\", "g");

function matcher(glob) {
  let build = (_i, _out) => {
    while (true) {
      let out = _out;
      let i = _i;
      if (i >= glob.length) {
        return out;
      }
      if (glob.charAt(i) !== "*") {
        _out = out + glob.charAt(i).replace(special, "\\$&");
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 1 | 0) !== "*") {
        _out = out + "[^/]*";
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 2 | 0) === "/") {
        _out = out + "(?:.*/)?";
        _i = i + 3 | 0;
        continue;
      }
      _out = out + ".*";
      _i = i + 2 | 0;
      continue;
    };
  };
  let re = new RegExp(`^` + build(0, "") + `$`);
  return name => re.test(name.replace(slashes, "/"));
}

function normalize(path) {
  let rooted = path.startsWith("/");
  let parts = Stdlib_Array.reduce(path.split("/"), [], (acc, s) => {
    let match = acc.at(-1);
    switch (s) {
      case "" :
      case "." :
        return acc;
      case ".." :
        if (match !== undefined && match !== "..") {
          return acc.slice(0, acc.length - 1 | 0);
        }
        if (rooted) {
          return acc;
        } else {
          return Belt_Array.concatMany([
            acc,
            [s]
          ]);
        }
      default:
        return Belt_Array.concatMany([
          acc,
          [s]
        ]);
    }
  });
  return (
    rooted ? "/" : ""
  ) + parts.join("/");
}

let matter = new RegExp("^---\\n(?:([\\s\\S]*?)\\n)?---(?:\\n|$)");

function split(text, at) {
  if (!text.startsWith("---\n")) {
    return {
      front: {},
      body: text,
      pad: 0
    };
  }
  let m = matter.exec(text);
  if (m == null) {
    return Schema.fail(at + `: unterminated frontmatter (missing closing "---" line)`);
  }
  let match = m.slice(1)[0];
  let vars;
  if (match !== undefined) {
    let head = Primitive_option.valFromOption(match);
    vars = head !== undefined ? Schema.front(head, at) : ({});
  } else {
    vars = {};
  }
  let full = m[0];
  let pad = full.split("\n").length - 1 | 0;
  return {
    front: vars,
    body: "\n".repeat(pad) + text.slice(full.length),
    pad: pad
  };
}

function infer(path) {
  if (path.endsWith(".md") || path.endsWith(".markdown")) {
    return "md";
  } else if (path.endsWith(".html") || path.endsWith(".htm")) {
    return "none";
  } else {
    return;
  }
}

async function seq(xs, i, fn) {
  if (i < xs.length) {
    await fn(xs[i]);
    return await seq(xs, i + 1 | 0, fn);
  }
}

function strs(vars, parent) {
  let get = name => {
    let match = vars[name];
    if (match !== undefined && match.TAG === "Scalar") {
      return {
        TAG: "One",
        _0: render(match._0, get)
      };
    } else {
      return parent(name);
    }
  };
  return get;
}

function named(transforms, name, at) {
  let t = transforms[name];
  if (t !== undefined) {
    return Primitive_option.valFromOption(t);
  } else {
    return Schema.fail(at + `: unknown transform "` + name + `" (available: ` + Object.keys(transforms).join(", ") + `)`);
  }
}

async function content(fs, transforms, path, explicit, at) {
  if (!await fs.exists(path)) {
    Schema.fail(`Content file not found: ` + path + ` (declared at ` + at + `)`);
  }
  let match = split(await fs.readFile(path), path);
  let name = Stdlib_Option.orElse(explicit, infer(path));
  let name$1 = name !== undefined ? name : Schema.fail(at + `: cannot infer a transform for ` + path + ` — set "transform" (available: ` + Object.keys(transforms).join(", ") + `)`);
  return {
    body: match.body,
    transform: named(transforms, name$1, at),
    front: match.front,
    at: `file ` + path,
    pad: match.pad,
    path: path
  };
}

async function listing(fs, transforms, pget, src, at) {
  let dir = top(at + ` dir`, () => render(src.dir, pget));
  let glob = Stdlib_Option.getOr(src.glob, "*.md");
  let names = (await fs.listFiles(dir)).filter(matcher(glob));
  if (names.length === 0 && !Stdlib_Option.getOr(src.optional, false)) {
    Schema.fail(`No files matching "` + glob + `" in ` + dir + ` (declared at ` + at + `)`);
  }
  return [
    dir,
    await Promise.all(names.map(n => content(fs, transforms, Schema.join(dir, n), src.transform, at)))
  ];
}

async function load(fs, transforms, pget, label, vars) {
  let out = {};
  let $$exports = {};
  let owners = {};
  await seq(Object.entries(vars), 0, async param => {
    let v = param[1];
    let name = param[0];
    let at = label + `.` + name;
    switch (v.TAG) {
      case "Scalar" :
        out[name] = {
          TAG: "T",
          _0: v._0
        };
        return;
      case "Scalars" :
        out[name] = {
          TAG: "L",
          _0: v._0
        };
        return;
      case "FileV" :
        let f = v._0;
        let path = top(at + ` file`, () => render(f.file, pget));
        let c = await content(fs, transforms, path, f.transform, at);
        Object.entries(data(c.front)).forEach(param => {
          let fname = param[0];
          let owner = owners[fname];
          if (owner !== undefined && owner !== path) {
            Schema.fail(`Frontmatter conflict in ` + label + `: "` + fname + `" defined by both ` + owner + ` and ` + path);
          }
          owners[fname] = path;
          $$exports[fname] = param[1];
        });
        out[name] = {
          TAG: "F",
          _0: c
        };
        return;
      case "DirV" :
        let d = v._0;
        let src_dir = d.dir;
        let src_glob = d.glob;
        let src_transform = d.transform;
        let src_optional = d.optional;
        let src = {
          dir: src_dir,
          glob: src_glob,
          transform: src_transform,
          optional: src_optional
        };
        let match = await listing(fs, transforms, pget, src, at);
        out[name] = {
          TAG: "D",
          _0: match[1],
          _1: Stdlib_Option.getOr(d.each, "{{body}}"),
          _2: `dir ` + match[0] + ` (` + at + `)`
        };
        return;
      case "ListV" :
        out[name] = {
          TAG: "R",
          _0: v._0,
          _1: at
        };
        return;
      case "PipeV" :
        let p = v._0;
        out[name] = {
          TAG: "P",
          _0: p.value,
          _1: named(transforms, p.transform, at),
          _2: at
        };
        return;
    }
  });
  return [
    out,
    $$exports
  ];
}

async function chain(fs, path, visited, from) {
  if (visited.includes(path)) {
    Schema.fail(`Base config cycle: ` + Belt_Array.concatMany([
      visited,
      [path]
    ]).join(" -> "));
  }
  if (!await fs.exists(path)) {
    Schema.fail(`Config not found: ` + path + (
      from === "" ? "" : ` (base of ` + from + `)`
    ));
  }
  let config = Schema.parse(await fs.readFile(path), path);
  let base = config.base;
  if (base !== undefined) {
    return (await chain(fs, base, Belt_Array.concatMany([
      visited,
      [path]
    ]), path)).concat([config]);
  } else {
    return [config];
  }
}

async function exec(fs, transforms, inline, entry) {
  let configs = await chain(fs, entry, [], "");
  let pget = Stdlib_Array.reduce(configs, param => {}, (parent, c) => strs(c.vars, parent));
  let grow = async (acc, i) => {
    if (i >= configs.length) {
      return acc;
    }
    let match = await load(fs, transforms, pget, `var (` + entry + `)`, configs[i].vars);
    let parent = Object.assign(Object.assign({}, acc), match[1]);
    return await grow(Object.assign(Object.assign({}, parent), match[0]), i + 1 | 0);
  };
  let shared = await grow({}, 0);
  let last = configs[configs.length - 1 | 0];
  let plans = await Promise.all(last.build.map(async (b, i) => {
    let at = `build[` + i.toString() + `]`;
    let bpget = strs(b.vars, pget);
    let match = await load(fs, transforms, bpget, at + `.var`, b.vars);
    let $$exports = match[1];
    let own = match[0];
    let match$1 = b.input;
    let match$2 = b.pages;
    if (match$1.TAG === "Copy") {
      let path = match$1._0;
      if (match$2 !== undefined) {
        return Schema.fail(at + `: "pages" cannot be combined with a copy input`);
      }
      let source = top(at + ` input copy`, () => render(path, bpget));
      if (!await fs.exists(source)) {
        Schema.fail(`Copy source not found: ` + source + ` (declared at ` + at + ` input)`);
      }
      let parent = Object.assign(Object.assign({}, shared), $$exports);
      let ctx = make(inline, Object.assign(Object.assign({}, parent), own));
      let output = top(at + ` output`, () => render(b.output, ctx.get));
      return [{
          output: output,
          by: at,
          copy: true,
          write: () => fs.copy(source, output)
        }];
    }
    let match$3;
    switch (match$1.TAG) {
      case "Text" :
        match$3 = [
          {
            TAG: "T",
            _0: match$1._0
          },
          {}
        ];
        break;
      case "FileI" :
        let f = match$1._0;
        let path$1 = top(at + ` input file`, () => render(f.file, bpget));
        let match$4 = await load(fs, transforms, bpget, at, Object.fromEntries([[
            "input",
            {
              TAG: "FileV",
              _0: {
                file: path$1,
                transform: f.transform
              }
            }
          ]]));
        let match$5 = match$4[0]["input"];
        if (match$5 !== undefined) {
          if (match$5.TAG === "F") {
            let c = match$5._0;
            match$3 = [
              {
                TAG: "F",
                _0: c
              },
              data(c.front)
            ];
          } else {
            match$3 = [
              {
                TAG: "T",
                _0: ""
              },
              {}
            ];
          }
        } else {
          match$3 = [
            {
              TAG: "T",
              _0: ""
            },
            {}
          ];
        }
        break;
      case "DirI" :
        let match$6 = await load(fs, transforms, bpget, at, Object.fromEntries([[
            "input",
            {
              TAG: "DirV",
              _0: match$1._0
            }
          ]]));
        let match$7 = match$6[0]["input"];
        match$3 = match$7 !== undefined ? (
            match$7.TAG === "D" ? [
                {
                  TAG: "D",
                  _0: match$7._0,
                  _1: match$7._1,
                  _2: match$7._2
                },
                {}
              ] : [
                {
                  TAG: "T",
                  _0: ""
                },
                {}
              ]
          ) : [
            {
              TAG: "T",
              _0: ""
            },
            {}
          ];
        break;
      case "Copy" :
        match$3 = [
          {
            TAG: "T",
            _0: ""
          },
          {}
        ];
        break;
    }
    let lv = match$3[0];
    let parent$1 = Object.assign(Object.assign({}, match$3[1]), shared);
    let base = Object.assign(Object.assign({}, parent$1), $$exports);
    let job = (layer, page) => {
      let parent = Object.assign(Object.assign({}, base), layer);
      let ctx = make(inline, Object.assign(Object.assign({}, parent), own));
      let output = top(at + ` output` + page, () => render(b.output, ctx.get));
      let write = async () => {
        let out = rawBoxed(stack, inline, () => {
          let s = top(at + ` input` + page, () => $$eval(lv, ctx));
          if (s.TAG === "One") {
            return s._0;
          } else {
            return s._0.join("");
          }
        });
        return await fs.writeFile(output, out);
      };
      return {
        output: output,
        by: at + page,
        copy: false,
        write: write
      };
    };
    if (match$2 === undefined) {
      return [job({}, "")];
    }
    let match$8 = await listing(fs, transforms, bpget, match$2, at + `.pages`);
    return match$8[1].map(c => {
      let own = Object.fromEntries([[
          "page",
          {
            TAG: "F",
            _0: c
          }
        ]]);
      let own$1 = data(c.front);
      let parent = naming(c);
      let parent$1 = Object.assign(Object.assign({}, parent), own$1);
      return job(Object.assign(Object.assign({}, parent$1), own), ` (page ` + c.path + `)`);
    });
  }));
  let jobs = plans.flat();
  let owners = {};
  jobs.forEach(j => {
    let key = normalize(j.output);
    let o = owners[key];
    if (o !== undefined && !(o.copy && j.copy)) {
      return Schema.fail(`Output path collision: ` + key + ` is written by both ` + o.by + ` and ` + j.by);
    } else {
      owners[key] = j;
      return;
    }
  });
  await Promise.all(jobs.map(j => j.write()));
}

function makeMemoryFileSystem(seed) {
  let files = Object.assign({}, Stdlib_Option.getOr(seed, {}));
  let sorted = keys => keys.toSorted(Primitive_string.compare);
  return {
    readFile: async path => {
      let content = files[path];
      if (content !== undefined) {
        return content;
      } else {
        return Schema.fail(`File not found: ` + path);
      }
    },
    writeFile: async (path, content) => {
      files[path] = content;
    },
    copy: async (source, output) => {
      let content = files[source];
      if (content !== undefined) {
        files[output] = content;
        return;
      }
      let prefix = source + `/`;
      let hits = Object.entries(files).filter(param => param[0].startsWith(prefix));
      if (hits.length === 0) {
        Schema.fail(`File not found: ` + source);
      }
      hits.forEach(param => {
        files[output + `/` + param[0].slice(prefix.length)] = param[1];
      });
    },
    exists: async path => {
      let match = files[path];
      if (match !== undefined) {
        return true;
      } else {
        return Object.keys(files).some(f => f.startsWith(path + `/`));
      }
    },
    glob: async pattern => sorted(Object.keys(files).filter(matcher(pattern))),
    listFiles: async dir => {
      let prefix = dir === "" ? "" : dir + `/`;
      return sorted(Object.keys(files).filter(p => {
        if (p.startsWith(prefix)) {
          return !p.slice(prefix.length).includes("/");
        } else {
          return false;
        }
      }).map(p => p.slice(prefix.length)));
    }
  };
}

let import_ = ((name) => import(name));

function nodeFs(root) {
  let cache = {
    contents: undefined
  };
  let mods = () => {
    let loaded = cache.contents;
    if (loaded !== undefined) {
      return loaded;
    }
    let loaded$1 = (async () => {
      let fs = await import_("node:fs/promises");
      let base;
      if (root !== undefined) {
        if (typeof root === "string") {
          base = root.startsWith("/") ? root : Schema.join(process.cwd(), root);
        } else {
          let url = await import_("node:url");
          base = url.fileURLToPath(root);
        }
      } else {
        base = process.cwd();
      }
      return [
        fs,
        base
      ];
    })();
    cache.contents = loaded$1;
    return loaded$1;
  };
  let absolute = (base, path) => {
    if (path.startsWith("/")) {
      return path;
    } else {
      return Schema.join(base, path);
    }
  };
  let canonical = path => "/" + Stdlib_Array.reduce(path.split("/"), [], (acc, s) => {
    switch (s) {
      case "" :
      case "." :
        return acc;
      case ".." :
        return acc.slice(0, acc.length - 1 | 0);
      default:
        return Belt_Array.concatMany([
          acc,
          [s]
        ]);
    }
  }).join("/");
  let copying = {};
  return {
    readFile: async path => {
      let match = await mods();
      return await match[0].readFile(absolute(match[1], path), "utf8");
    },
    writeFile: async (path, content) => {
      let match = await mods();
      let fs = match[0];
      let file = absolute(match[1], path);
      await fs.mkdir(Schema.dirname(file), {
        recursive: true
      });
      return await fs.writeFile(file, content, "utf8");
    },
    copy: async (source, output) => {
      let match = await mods();
      let base = match[1];
      let fs = match[0];
      let target = canonical(absolute(base, output));
      let previous = Stdlib_Option.getOr(copying[target], Promise.resolve());
      let current = (async () => {
        try {
          await previous;
        } catch (exn) {
          
        }
        await fs.mkdir(Schema.dirname(target), {
          recursive: true
        });
        return await fs.cp(absolute(base, source), target, {
          recursive: true
        });
      })();
      copying[target] = current;
      return await current;
    },
    exists: async path => {
      let match = await mods();
      try {
        await match[0].access(absolute(match[1], path));
        return true;
      } catch (exn) {
        return false;
      }
    },
    glob: async pattern => {
      let match = await mods();
      let base = match[1];
      let entries;
      try {
        entries = await match[0].readdir(base, {
          withFileTypes: true,
          recursive: true
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(e => (e.parentPath + `/` + e.name).slice(base.length + 1 | 0).replace(slashes, "/")).filter(matcher(pattern)).toSorted(Primitive_string.compare);
    },
    listFiles: async dir => {
      let match = await mods();
      let entries;
      try {
        entries = await match[0].readdir(absolute(match[1], dir), {
          withFileTypes: true,
          recursive: false
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(__x => __x.name).toSorted(Primitive_string.compare);
    }
  };
}

async function run(options) {
  let inline = Stdlib_Option.getOr(options.inlineErrors, false);
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : nodeFs(undefined);
  let configs = await fs$1.glob(options.glob);
  if (configs.length === 0) {
    Schema.fail(`No config files match "` + options.glob + `"`);
  }
  let transforms = Object.assign(Object.assign({}, defaults), Stdlib_Option.getOr(options.transform, {}));
  await Promise.all(configs.toSorted(Primitive_string.compare).map(config => exec(fs$1, transforms, inline, config)));
}

async function entry(fs, glob) {
  let path = (await fs.glob(glob)).toSorted(Primitive_string.compare)[0];
  if (path !== undefined) {
    return path;
  } else {
    return Schema.fail(`No config files match "` + glob + `"`);
  }
}

async function watch(options) {
  let root = Stdlib_Option.getOr(options.root, process.cwd());
  let path = options.build;
  let rebuild = path !== undefined ? () => Dev.script(path, root) : () => run({
      glob: options.glob,
      fs: options.fs,
      transform: options.transform,
      inlineErrors: options.inlineErrors
    });
  return await Dev.watch({
    root: root,
    watch: options.watch,
    ignore: options.ignore,
    extensions: options.extensions
  }, rebuild);
}

async function dev(options) {
  let root = Stdlib_Option.getOr(options.root, process.cwd());
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : nodeFs(undefined);
  let path = options.build;
  let rebuild = path !== undefined ? () => Dev.script(path, root) : () => run({
      glob: options.glob,
      fs: options.fs,
      transform: options.transform,
      inlineErrors: Stdlib_Option.getOr(options.inlineErrors, true)
    });
  return await Dev.dev({
    root: root,
    watch: options.watch,
    ignore: options.ignore,
    extensions: options.extensions,
    serve: options.serve,
    port: options.port
  }, {
    rebuild: rebuild,
    readPort: async () => Schema.port(await fs$1.readFile(await entry(fs$1, options.glob))),
    writePort: async port => {
      let path = await entry(fs$1, options.glob);
      return await fs$1.writeFile(path, Schema.withPort(await fs$1.readFile(path), port));
    }
  });
}

export {
  run,
  makeMemoryFileSystem,
  nodeFs,
  watch,
  dev,
}
/* defaults Not a pure module */
