// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dev from "./Dev.res.mjs";
import * as Tilia from "tilia/src/Tilia.res.mjs";
import * as Schema from "./Schema.res.mjs";
import * as Marked from "marked";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

let defaults = Object.fromEntries([
  [
    "md",
    text => Marked.marked.parse(text, {
      async: false
    })
  ],
  [
    "none",
    text => text
  ]
]);

let reference = new RegExp("\\{\\{\\s*(`?)([A-Za-z_][A-Za-z0-9_.-]*)\\1\\s*\\}\\}", "g");

let backtick = new RegExp("`", "g");

let stack = {
  contents: []
};

let cycle = {
  contents: undefined
};

let pending = (() => { throw { minidocPending: true } });

let attempt = ((fn) => {
  try { return fn() } catch (e) { if (e && e.minidocPending) return undefined; throw e }
});

let capture = (async (load) => {
  try { return { ok: true, value: await load() } } catch (e) { return { ok: false, value: e } }
});

let rethrow = ((e) => { throw e });

let loud = ((message) => {
  const e = new Error(message); e.minidocSited = true; throw e
});

let rawSite = ((at, fn) => {
  try { return fn() } catch (e) {
    if (e && e.message && !e.minidocSited) {
      e.minidocSited = true
      e.message = e.message.startsWith("Variable cycle:")
        ? "Variable cycle in " + at + ":" + e.message.slice(15)
        : e.message + " in " + at
    }
    throw e
  }
});

let rawBoxed = ((stack, inline, fn) => {
  if (!inline) return fn()
  const active = stack.contents
  try { return fn() } catch (e) {
    stack.contents = active
    if (e && e.minidocPending) throw e
    const message = String((e && e.message) || e)
    console.error("minidoc: " + message)
    const text = message.replace(/&/g, "&amp;").replace(/</g, "&lt;")
    return '<div class="minidoc-error" style="border:1px solid #c00;background:rgba(255,0,0,.04);padding:.5em .75em;font-family:monospace;white-space:pre-wrap;">' + text + '</div>'
  }
});

function all(xs, f) {
  let stalled = {
    contents: false
  };
  let out = xs.map(x => {
    let v = attempt(() => f(x));
    if (v !== undefined) {
      return Primitive_option.some(Primitive_option.valFromOption(v));
    } else {
      stalled.contents = true;
      return;
    }
  });
  if (stalled.contents) {
    pending();
  }
  return Stdlib_Array.filterMap(out, v => v);
}

function need(env, key, load) {
  let match = env.cache[key];
  if (match !== undefined) {
    if (match.ok) {
      return match.value;
    } else {
      return rethrow(match.value);
    }
  } else {
    if (!(key in env.started)) {
      env.started[key] = capture(load).then(o => {
        env.cache[key] = o;
      });
    }
    return pending();
  }
}

async function settle(env, fn) {
  let v = attempt(fn);
  if (v !== undefined) {
    return Primitive_option.valFromOption(v);
  }
  let before = Object.keys(env.cache).length;
  await Promise.all(Object.values(env.started));
  if (Object.keys(env.cache).length === before) {
    Schema.fail("minidoc: render stalled with no read pending");
  }
  return await settle(env, fn);
}

function lined(template, offset) {
  if (template.includes("\n")) {
    return ` at line ` + template.slice(0, offset).split("\n").length.toString();
  } else {
    return "";
  }
}

function unpad(text, pad) {
  let go = _i => {
    while (true) {
      let i = _i;
      if (!(i < pad && text.charAt(i) === "\n")) {
        return i;
      }
      _i = i + 1 | 0;
      continue;
    };
  };
  return text.slice(go(0));
}

function nodes(trees, origin) {
  let out = {};
  Stdlib_Dict.forEachWithKey(trees, (t, key) => {
    let n;
    switch (t.TAG) {
      case "Str" :
        n = {
          TAG: "Leaf",
          _0: t._0,
          _1: origin
        };
        break;
      case "Strs" :
        n = {
          TAG: "List",
          _0: t._0,
          _1: origin
        };
        break;
      case "Tree" :
        n = {
          TAG: "Group",
          _0: nodes(t._0, origin)
        };
        break;
    }
    place(out, key.split("."), n, key, origin);
  });
  return out;
}

function place(_out, _path, n, key, origin) {
  while (true) {
    let path = _path;
    let out = _out;
    let head = path[0];
    let twice = () => Schema.fail(origin.label + `: "` + key + `" is defined twice`);
    if (path.length === 1) {
      let match = out[head];
      if (match !== undefined) {
        if (match.TAG !== "Group") {
          return twice();
        }
        if (n.TAG !== "Group") {
          return twice();
        }
        let into = match._0;
        return Stdlib_Dict.forEachWithKey(n._0, (m, k) => place(into, [k], m, key + `.` + k, origin));
      }
      out[head] = n;
      return;
    }
    let match$1 = out[head];
    let into$1;
    if (match$1 !== undefined) {
      into$1 = match$1.TAG === "Group" ? match$1._0 : twice();
    } else {
      let d = {};
      out[head] = {
        TAG: "Group",
        _0: d
      };
      into$1 = d;
    }
    _path = path.slice(1);
    _out = into$1;
    continue;
  };
}

function merge(parent, own) {
  let out = Object.assign({}, parent);
  Stdlib_Dict.forEachWithKey(own, (n, k) => {
    let match = out[k];
    if (match !== undefined && match.TAG === "Group" && n.TAG === "Group") {
      out[k] = {
        TAG: "Group",
        _0: merge(match._0, n._0)
      };
      return;
    }
    out[k] = n;
  });
  return out;
}

function reanchor(tree, origin) {
  return Stdlib_Dict.mapValues(tree, n => {
    switch (n.TAG) {
      case "Leaf" :
        return {
          TAG: "Leaf",
          _0: n._0,
          _1: origin
        };
      case "List" :
        return {
          TAG: "List",
          _0: n._0,
          _1: origin
        };
      case "Group" :
        return {
          TAG: "Group",
          _0: reanchor(n._0, origin)
        };
      case "Fixed" :
      case "Body" :
        return n;
    }
  });
}

function paths(tree) {
  let out = {};
  let go = (tree, prefix) => Stdlib_Dict.forEachWithKey(tree, (n, k) => {
    let p = prefix === "" ? k : prefix + `.` + k;
    out[p] = n;
    if (n.TAG === "Group") {
      return go(n._0, p);
    }
  });
  go(tree, "");
  return out;
}

function basename(path) {
  return path.slice(path.lastIndexOf("/") + 1 | 0);
}

function naming(c) {
  let name = basename(c.path);
  let dot = name.lastIndexOf(".");
  let stem = dot > 0 ? name.slice(0, dot) : name;
  let s = basename(Schema.dirname(c.path));
  let pairs = [
    [
      "name",
      {
        TAG: "Fixed",
        _0: {
          TAG: "One",
          _0: name
        }
      }
    ],
    [
      "stem",
      {
        TAG: "Fixed",
        _0: {
          TAG: "One",
          _0: stem
        }
      }
    ],
    [
      "dir",
      {
        TAG: "Fixed",
        _0: {
          TAG: "One",
          _0: s
        }
      }
    ]
  ];
  return Object.fromEntries([[
      "file",
      {
        TAG: "Group",
        _0: Object.fromEntries(pairs)
      }
    ]]);
}

let special = new RegExp("[.*+?^${}()|[\\]\\\\]", "g");

let slashes = new RegExp("\\\\", "g");

function matcher(glob) {
  let build = (_i, _out) => {
    while (true) {
      let out = _out;
      let i = _i;
      if (i >= glob.length) {
        return out;
      }
      if (glob.charAt(i) !== "*") {
        _out = out + glob.charAt(i).replace(special, "\\$&");
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 1 | 0) !== "*") {
        _out = out + "[^/]*";
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 2 | 0) === "/") {
        _out = out + "(?:.*/)?";
        _i = i + 3 | 0;
        continue;
      }
      _out = out + ".*";
      _i = i + 2 | 0;
      continue;
    };
  };
  let re = new RegExp(`^` + build(0, "") + `$`);
  return name => re.test(name.replace(slashes, "/"));
}

function normalize(path) {
  let rooted = path.startsWith("/");
  let parts = Stdlib_Array.reduce(path.split("/"), [], (acc, s) => {
    let match = acc.at(-1);
    switch (s) {
      case "" :
      case "." :
        return acc;
      case ".." :
        if (match !== undefined && match !== "..") {
          return acc.slice(0, acc.length - 1 | 0);
        }
        if (rooted) {
          return acc;
        } else {
          return Belt_Array.concatMany([
            acc,
            [s]
          ]);
        }
      default:
        return Belt_Array.concatMany([
          acc,
          [s]
        ]);
    }
  });
  return (
    rooted ? "/" : ""
  ) + parts.join("/");
}

let matter = new RegExp("^---\\n(?:([\\s\\S]*?)\\n)?---(?:\\n|$)");

function split(text, path) {
  let at = `file ` + path;
  let parsed;
  if (text.startsWith("---\n")) {
    let m = matter.exec(text);
    parsed = (m == null) ? Schema.fail(path + `: unterminated frontmatter (missing closing "---" line)`) : m;
  } else {
    parsed = undefined;
  }
  if (parsed === undefined) {
    return {
      body: text,
      front: {},
      at: at,
      pad: 0,
      path: path
    };
  }
  let match = parsed.slice(1)[0];
  let trees;
  if (match !== undefined) {
    let head = Primitive_option.valFromOption(match);
    trees = head !== undefined ? Schema.front(head, path) : ({});
  } else {
    trees = {};
  }
  let full = parsed[0];
  let pad = full.split("\n").length - 1 | 0;
  return {
    body: "\n".repeat(pad) + text.slice(full.length),
    front: nodes(trees, {
      dir: Schema.dirname(path),
      label: at
    }),
    at: at,
    pad: pad,
    path: path
  };
}

function infer(path) {
  if (path.endsWith(".md") || path.endsWith(".markdown")) {
    return "md";
  } else if (path.endsWith(".html") || path.endsWith(".htm")) {
    return "none";
  } else {
    return;
  }
}

function named(transforms, name, at) {
  let t = transforms[name];
  if (t !== undefined) {
    return Primitive_option.valFromOption(t);
  } else {
    return Schema.fail(at + `: unknown transform "` + name + `" (available: ` + Object.keys(transforms).join(", ") + `)`);
  }
}

function transformOf(transforms, path, explicit, at) {
  let name = Stdlib_Option.orElse(explicit, infer(path));
  if (name !== undefined) {
    return named(transforms, name, at);
  } else {
    return Schema.fail(at + `: cannot infer a transform for ` + path + ` — set "transform" (available: ` + Object.keys(transforms).join(", ") + `)`);
  }
}

function read(env, path) {
  return need(env, `read:` + path, async () => {
    if (await env.fs.exists(path)) {
      return split(await env.fs.readFile(path), path);
    }
  });
}

function exists(env, path) {
  return need(env, `exists:` + path, () => env.fs.exists(path));
}

function files(env, dir) {
  return need(env, `files:` + dir, () => env.fs.listFiles(dir));
}

function folders(env, dir) {
  return need(env, `dirs:` + dir, () => env.fs.listDirs(dir));
}

function ordered(names, order) {
  if (Primitive_object.equal(order, "desc")) {
    return names.toReversed();
  } else {
    return names;
  }
}

function walk(env, dir, prefix) {
  let here = prefix === "" ? dir : Schema.join(dir, prefix);
  let own = attempt(() => files(env, here));
  let subs = attempt(() => folders(env, here));
  if (own !== undefined && subs !== undefined) {
    return own.map(__x => Schema.join(prefix, __x)).concat(all(subs, d => walk(env, dir, Schema.join(prefix, d))).flat());
  } else {
    return pending();
  }
}

function listing(env, dir, glob, order, optional, at) {
  let deep = glob.includes("/") || glob.includes("**");
  let names = ordered((
    deep ? walk(env, dir, "") : files(env, dir)
  ).filter(matcher(glob)).toSorted(Primitive_string.compare), order);
  if (names.length === 0 && !optional) {
    loud(`No files matching "` + glob + `" in ` + dir + ` (declared at ` + at + `)`);
  }
  return all(names, n => {
    let path = Schema.join(dir, n);
    let c = read(env, path);
    if (c !== undefined) {
      return c;
    } else {
      return loud(`Content file not found: ` + path + ` (declared at ` + at + `)`);
    }
  });
}

function top(at, fn) {
  stack.contents = [];
  cycle.contents = undefined;
  return rawSite(at, fn);
}

let kinds = [
  "file",
  "dir",
  "dirs",
  "list",
  "value"
];

function make(env, inline, tree) {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      env: env,
      inline: inline,
      tree: tree,
      vars: Object.fromEntries(Object.entries(paths(tree)).map(param => {
        let n = param[1];
        let p = param[0];
        return [
          p,
          derived(self => $$eval(n, p, self))
        ];
      })),
      get: derived(self => (name => {
        let d = self.vars[name];
        if (d !== undefined) {
          return d;
        } else {
          let segments = name.split(".");
          let _d = self.tree;
          let _i = 0;
          while (true) {
            let i = _i;
            let d$1 = _d;
            let match = d$1[segments[i]];
            if (match !== undefined) {
              if (match.TAG !== "Group") {
                return;
              }
              if ((i + 1 | 0) >= segments.length) {
                return;
              }
              _i = i + 1 | 0;
              _d = match._0;
              continue;
            }
            if (!(i > 0 && "file" in d$1)) {
              return;
            }
            let p = segments.slice(0, i).join(".");
            return Stdlib_Option.flatMap(load(d$1, p, self), c => sub(self, c.front).get(segments.slice(i).join(".")));
          };
        }
      }))
    };
  });
}

function sub(self, layer) {
  return make(self.env, self.inline, merge(self.tree, layer));
}

function $$eval(n, p, self) {
  switch (n.TAG) {
    case "Leaf" :
      return {
        TAG: "One",
        _0: render(n._0, self.get)
      };
    case "List" :
      return {
        TAG: "Many",
        _0: n._0.map(__x => render(__x, self.get))
      };
    case "Group" :
      let d = n._0;
      let several = kinds.filter(k => k in d);
      let len = several.length;
      if (len !== 1) {
        if (len === 0) {
          return Schema.fail(`{{` + p + `}} is a group (` + Object.keys(d).join(", ") + `), not a value`);
        }
      } else {
        let match = several[0];
        switch (match) {
          case "dir" :
            let where = at(d, "dir", p);
            let folder = path(d, "dir", p, self);
            let glob = Stdlib_Option.getOr(text(d, "glob", p, self), "*.md");
            let explicit = text(d, "transform", p, self);
            let each = Stdlib_Option.getOr(raw(d, "each", p), "{{body}}");
            let items = listing(self.env, folder, glob, order(d, "dir", p, self), flag(d, "optional", p, self), where);
            let site_ = `dir ` + folder + ` (` + where + `)`;
            return {
              TAG: "One",
              _0: rawSite(site_, () => items.map(c => rawBoxed(stack, self.inline, () => rawSite(site_, () => {
                let transform = transformOf(self.env.transforms, c.path, explicit, where);
                let front = sub(self, merge(naming(c), c.front));
                let body = unpad(transform(rawSite(c.at, () => render(c.body, front.get))), c.pad);
                return render(each, sub(front, Object.fromEntries([[
                    "body",
                    {
                      TAG: "Fixed",
                      _0: {
                        TAG: "One",
                        _0: body
                      }
                    }
                  ]])).get);
              }))).join(Stdlib_Option.getOr(raw(d, "join", p), "\n")))
            };
          case "dirs" :
            let where$1 = at(d, "dirs", p);
            let root = path(d, "dirs", p, self);
            let each$1 = raw(d, "each", p);
            let each$2 = each$1 !== undefined ? each$1 : Schema.fail(where$1 + `: "dirs" needs an "each" template`);
            let names = ordered(folders(self.env, root).toSorted(Primitive_string.compare), order(d, "dirs", p, self));
            if (names.length === 0 && !flag(d, "optional", p, self)) {
              loud(`No folders in ` + root + ` (declared at ` + where$1 + `)`);
            }
            let match$1 = d["var"];
            let vars = match$1 !== undefined ? (
                match$1.TAG === "Group" ? match$1._0 : ({})
              ) : ({});
            let match$2 = d["dirs"];
            let label = match$2 !== undefined ? (
                match$2.TAG === "Leaf" ? match$2._1.label + `.` + p + `.var` : p + `.var`
              ) : p + `.var`;
            return {
              TAG: "One",
              _0: rawSite(`dirs ` + root + ` (` + where$1 + `)`, () => names.map(n => {
                let folder = Schema.join(root, n);
                let layer = merge(Object.fromEntries([[
                    "folder",
                    {
                      TAG: "Group",
                      _0: Object.fromEntries([[
                          "name",
                          {
                            TAG: "Fixed",
                            _0: {
                              TAG: "One",
                              _0: n
                            }
                          }
                        ]])
                    }
                  ]]), reanchor(vars, {
                  dir: folder,
                  label: label
                }));
                return rawBoxed(stack, self.inline, () => rawSite(`folder ` + folder + ` (` + where$1 + `)`, () => render(each$2, sub(self, layer).get)));
              }).join(Stdlib_Option.getOr(raw(d, "join", p), "\n")))
            };
          case "file" :
            let where$2 = at(d, "file", p);
            let c = load(d, p, self);
            if (c === undefined) {
              return {
                TAG: "One",
                _0: ""
              };
            }
            let transform = transformOf(self.env.transforms, c.path, text(d, "transform", p, self), where$2);
            return {
              TAG: "One",
              _0: rawBoxed(stack, self.inline, () => rawSite(c.at, () => {
                let front = sub(self, c.front);
                let body = unpad(transform(render(c.body, front.get)), c.pad);
                let template = raw(d, "template", p);
                if (template !== undefined) {
                  if (body.trim() !== "") {
                    return rawSite(where$2 + ` template`, () => render(template, sub(front, Object.fromEntries([[
                        "body",
                        {
                          TAG: "Fixed",
                          _0: {
                            TAG: "One",
                            _0: body
                          }
                        }
                      ]])).get));
                  } else {
                    return "";
                  }
                } else {
                  return body;
                }
              }))
            };
          case "list" :
            let where$3 = at(d, "list", p);
            let name = Stdlib_Option.getOr(raw(d, "list", p), "");
            let each$3 = raw(d, "each", p);
            let each$4 = each$3 !== undefined ? each$3 : Schema.fail(where$3 + `: "list" needs an "each" template`);
            return {
              TAG: "One",
              _0: rawBoxed(stack, self.inline, () => rawSite(where$3, () => {
                let match = self.get(name);
                if (match === undefined) {
                  return Schema.fail(`Undefined variable {{` + name + `}}`);
                }
                if (match.TAG === "One") {
                  return Schema.fail(`"` + name + `" must resolve to a scalar list`);
                }
                let items = match._0;
                if (items.length === 0) {
                  return "";
                }
                let one = (key, value, template) => render(template, sub(self, Object.fromEntries([[
                    key,
                    {
                      TAG: "Fixed",
                      _0: {
                        TAG: "One",
                        _0: value
                      }
                    }
                  ]])).get);
                let body = items.map(item => one("item", item, each$4)).join(Stdlib_Option.getOr(raw(d, "join", p), ""));
                let template = raw(d, "template", p);
                if (template !== undefined) {
                  return one("body", body, template);
                } else {
                  return body;
                }
              }))
            };
          case "value" :
            let where$4 = at(d, "value", p);
            let template = Stdlib_Option.getOr(raw(d, "value", p), "");
            let name$1 = raw(d, "transform", p);
            let transform$1 = name$1 !== undefined ? named(self.env.transforms, name$1, where$4) : Schema.fail(where$4 + `: "value" needs a "transform"`);
            return {
              TAG: "One",
              _0: rawBoxed(stack, self.inline, () => rawSite(where$4, () => transform$1(render(template, self.get))))
            };
        }
      }
      return Schema.fail(`{{` + p + `}} has several kinds (` + several.join(", ") + `): keep one`);
    case "Fixed" :
      return n._0;
    case "Body" :
      let transform$2 = n._1;
      let c$1 = n._0;
      return {
        TAG: "One",
        _0: rawBoxed(stack, self.inline, () => rawSite(c$1.at, () => unpad(transform$2(render(c$1.body, sub(self, c$1.front).get)), c$1.pad)))
      };
  }
}

function at(d, key, p) {
  let match = d[key];
  if (match === undefined) {
    return p;
  }
  switch (match.TAG) {
    case "Leaf" :
    case "List" :
      break;
    default:
      return p;
  }
  return match._1.label + `.` + p;
}

function text(d, key, p, self) {
  let match = d[key];
  if (match !== undefined) {
    if (match.TAG === "Leaf") {
      return render(match._0, self.get);
    } else {
      return Schema.fail(at(d, key, p) + `: "` + key + `" must be a string`);
    }
  }
}

function raw(d, key, p) {
  let match = d[key];
  if (match !== undefined) {
    if (match.TAG === "Leaf") {
      return match._0;
    } else {
      return Schema.fail(at(d, key, p) + `: "` + key + `" must be a string`);
    }
  }
}

function path(d, key, p, self) {
  let match = d[key];
  if (match !== undefined && match.TAG === "Leaf") {
    let o = match._1;
    let s = match._0;
    return rawSite(at(d, key, p) + ` ` + key, () => render(Schema.join(o.dir, s), self.get));
  }
  return Schema.fail(at(d, key, p) + `: "` + key + `" must be a path`);
}

function flag(d, key, p, self) {
  let v = text(d, key, p, self);
  if (v === undefined) {
    return false;
  }
  switch (v) {
    case "false" :
      return false;
    case "true" :
      return true;
    default:
      return Schema.fail(at(d, key, p) + `: "` + key + `" must be true or false, got "` + v + `"`);
  }
}

function order(d, key, p, self) {
  let v = text(d, "order", p, self);
  if (v === undefined) {
    return;
  }
  switch (v) {
    case "asc" :
      return;
    case "desc" :
      return "desc";
    default:
      return Schema.fail(at(d, key, p) + `: "order" must be "asc" or "desc", got "` + v + `"`);
  }
}

function load(d, p, self) {
  let file = path(d, "file", p, self);
  let c = read(self.env, file);
  if (c !== undefined) {
    return c;
  } else if (flag(d, "optional", p, self)) {
    return;
  } else {
    return loud(`Content file not found: ` + file + ` (declared at ` + at(d, "file", p) + `)`);
  }
}

function render(template, get) {
  let stalled = {
    contents: false
  };
  let out = template.replace(reference, (ref, quote, name, offset, input) => {
    if (quote !== "") {
      return ref.replace(backtick, "");
    }
    let active = stack.contents;
    if (active.includes(name)) {
      let from = active.indexOf(name);
      let path = cycle.contents;
      let path$1 = path !== undefined ? path : Belt_Array.concatMany([
          active.slice(from),
          [name]
        ]).join(" -> ");
      cycle.contents = path$1;
      Schema.fail(`Variable cycle: ` + path$1);
    }
    stack.contents = Belt_Array.concatMany([
      active,
      [name]
    ]);
    let out = attempt(() => {
      let match = get(name);
      if (match !== undefined) {
        if (match.TAG === "One") {
          return match._0;
        } else {
          return match._0.join("");
        }
      } else {
        return Schema.fail(`Undefined variable ` + ref + lined(input, offset));
      }
    });
    stack.contents = active;
    if (out !== undefined) {
      return out;
    } else {
      stalled.contents = true;
      return "";
    }
  });
  if (stalled.contents) {
    pending();
  }
  return out;
}

async function chain(fs, path, visited, from) {
  if (visited.includes(path)) {
    Schema.fail(`Base config cycle: ` + Belt_Array.concatMany([
      visited,
      [path]
    ]).join(" -> "));
  }
  if (!await fs.exists(path)) {
    Schema.fail(`Config not found: ` + path + (
      from === "" ? "" : ` (base of ` + from + `)`
    ));
  }
  let config = Schema.parse(await fs.readFile(path), path);
  let base = config.base;
  if (base !== undefined) {
    return (await chain(fs, base, Belt_Array.concatMany([
      visited,
      [path]
    ]), path)).concat([config]);
  } else {
    return [config];
  }
}

async function exec(fs, transforms, inline, entry) {
  let configs = await chain(fs, entry, [], "");
  let env_cache = {};
  let env_started = {};
  let env = {
    fs: fs,
    transforms: transforms,
    cache: env_cache,
    started: env_started
  };
  let shared = Stdlib_Array.reduce(configs, {}, (acc, c) => merge(acc, nodes(c.vars, {
    dir: Schema.dirname(c.path),
    label: `var (` + c.path + `)`
  })));
  let last = configs[configs.length - 1 | 0];
  let here = Schema.dirname(last.path);
  let plans = await Promise.all(last.build.map(async (b, i) => {
    let at = `build[` + i.toString() + `]`;
    let own = nodes(b.vars, {
      dir: here,
      label: at + `.var`
    });
    let entryCtx = () => make(env, inline, merge(shared, own));
    let match = b.input;
    let match$1 = b.pages;
    switch (match.TAG) {
      case "Copy" :
        let path = match._0;
        if (match$1 !== undefined) {
          return Schema.fail(at + `: "pages" cannot be combined with a copy input`);
        }
        let match$2 = await settle(env, () => {
          let ctx = entryCtx();
          let source = top(at + ` input copy`, () => render(path, ctx.get));
          if (!exists(env, source)) {
            Schema.fail(`Copy source not found: ` + source + ` (declared at ` + at + ` input)`);
          }
          return [
            source,
            top(at + ` output`, () => render(b.output, ctx.get))
          ];
        });
        let output = match$2[1];
        let source = match$2[0];
        return [{
            output: output,
            by: at,
            copy: true,
            write: () => fs.copy(source, output)
          }];
      case "Text" :
      case "Node" :
        break;
    }
    let origin = {
      dir: here,
      label: at
    };
    let node;
    switch (match.TAG) {
      case "Text" :
      case "Copy" :
        node = {
          TAG: "Leaf",
          _0: match._0,
          _1: origin
        };
        break;
      case "Node" :
        let d = nodes(match._0, origin);
        if ("file" in d && ("optional" in d || "template" in d)) {
          Schema.fail(at + ` input: "optional" and "template" apply to file vars, not to a file input`);
        }
        node = {
          TAG: "Group",
          _0: d
        };
        break;
    }
    let context = layer => {
      let front;
      if (node.TAG === "Group") {
        let d = node._0;
        front = "file" in d ? Stdlib_Option.mapOr(load(d, "input", entryCtx()), {}, c => c.front) : ({});
      } else {
        front = {};
      }
      return make(env, inline, merge(merge(merge(front, shared), layer), own));
    };
    let job = async (layer, page) => {
      let output = await settle(env, () => top(at + ` output` + page, () => render(b.output, context(layer).get)));
      let write = async () => {
        let out = await settle(env, () => rawBoxed(stack, inline, () => {
          let s = top(at + ` input` + page, () => $$eval(node, "input", context(layer)));
          if (s.TAG === "One") {
            return s._0;
          } else {
            return s._0.join("");
          }
        }));
        return await fs.writeFile(output, out);
      };
      return {
        output: output,
        by: at + page,
        copy: false,
        write: write
      };
    };
    if (match$1 === undefined) {
      return [await job({}, "")];
    }
    let items = await settle(env, () => {
      let dir = top(at + `.pages dir`, () => render(match$1.dir, entryCtx().get));
      let glob = Stdlib_Option.getOr(match$1.glob, "*.md");
      return listing(env, dir, glob, match$1.order, Stdlib_Option.getOr(match$1.optional, false), at + `.pages`);
    });
    return await Promise.all(items.map(c => {
      let transform = transformOf(transforms, c.path, match$1.transform, at + `.pages`);
      return job(merge(merge(naming(c), c.front), Object.fromEntries([[
          "page",
          {
            TAG: "Body",
            _0: c,
            _1: transform
          }
        ]])), ` (page ` + c.path + `)`);
    }));
  }));
  let jobs = plans.flat();
  let owners = {};
  jobs.forEach(j => {
    let key = normalize(j.output);
    let o = owners[key];
    if (o !== undefined && !(o.copy && j.copy)) {
      return Schema.fail(`Output path collision: ` + key + ` is written by both ` + o.by + ` and ` + j.by);
    } else {
      owners[key] = j;
      return;
    }
  });
  await Promise.all(jobs.map(j => j.write()));
}

function makeMemoryFileSystem(seed) {
  let files = Object.assign({}, Stdlib_Option.getOr(seed, {}));
  let sorted = keys => keys.toSorted(Primitive_string.compare);
  return {
    readFile: async path => {
      let content = files[path];
      if (content !== undefined) {
        return content;
      } else {
        return Schema.fail(`File not found: ` + path);
      }
    },
    writeFile: async (path, content) => {
      files[path] = content;
    },
    copy: async (source, output) => {
      let content = files[source];
      if (content !== undefined) {
        files[output] = content;
        return;
      }
      let prefix = source + `/`;
      let hits = Object.entries(files).filter(param => param[0].startsWith(prefix));
      if (hits.length === 0) {
        Schema.fail(`File not found: ` + source);
      }
      hits.forEach(param => {
        files[output + `/` + param[0].slice(prefix.length)] = param[1];
      });
    },
    exists: async path => {
      let match = files[path];
      if (match !== undefined) {
        return true;
      } else {
        return Object.keys(files).some(f => f.startsWith(path + `/`));
      }
    },
    glob: async pattern => sorted(Object.keys(files).filter(matcher(pattern))),
    listFiles: async dir => {
      let prefix = dir === "" ? "" : dir + `/`;
      return sorted(Object.keys(files).filter(p => {
        if (p.startsWith(prefix)) {
          return !p.slice(prefix.length).includes("/");
        } else {
          return false;
        }
      }).map(p => p.slice(prefix.length)));
    },
    listDirs: async dir => {
      let prefix = dir === "" ? "" : dir + `/`;
      let names = {};
      Object.keys(files).forEach(p => {
        if (!p.startsWith(prefix)) {
          return;
        }
        let rest = p.slice(prefix.length);
        let slash = rest.indexOf("/");
        if (slash > 0) {
          names[rest.slice(0, slash)] = undefined;
          return;
        }
      });
      return sorted(Object.keys(names));
    }
  };
}

let import_ = ((name) => import(name));

function nodeFs(root) {
  let cache = {
    contents: undefined
  };
  let mods = () => {
    let loaded = cache.contents;
    if (loaded !== undefined) {
      return loaded;
    }
    let loaded$1 = (async () => {
      let fs = await import_("node:fs/promises");
      let base;
      if (root !== undefined) {
        if (typeof root === "string") {
          base = root.startsWith("/") ? root : Schema.join(process.cwd(), root);
        } else {
          let url = await import_("node:url");
          base = url.fileURLToPath(root);
        }
      } else {
        base = process.cwd();
      }
      return [
        fs,
        base
      ];
    })();
    cache.contents = loaded$1;
    return loaded$1;
  };
  let absolute = (base, path) => {
    if (path.startsWith("/")) {
      return path;
    } else {
      return Schema.join(base, path);
    }
  };
  let canonical = path => "/" + Stdlib_Array.reduce(path.split("/"), [], (acc, s) => {
    switch (s) {
      case "" :
      case "." :
        return acc;
      case ".." :
        return acc.slice(0, acc.length - 1 | 0);
      default:
        return Belt_Array.concatMany([
          acc,
          [s]
        ]);
    }
  }).join("/");
  let copying = {};
  return {
    readFile: async path => {
      let match = await mods();
      return await match[0].readFile(absolute(match[1], path), "utf8");
    },
    writeFile: async (path, content) => {
      let match = await mods();
      let fs = match[0];
      let file = absolute(match[1], path);
      await fs.mkdir(Schema.dirname(file), {
        recursive: true
      });
      return await fs.writeFile(file, content, "utf8");
    },
    copy: async (source, output) => {
      let match = await mods();
      let base = match[1];
      let fs = match[0];
      let target = canonical(absolute(base, output));
      let previous = Stdlib_Option.getOr(copying[target], Promise.resolve());
      let current = (async () => {
        try {
          await previous;
        } catch (exn) {
          
        }
        await fs.mkdir(Schema.dirname(target), {
          recursive: true
        });
        return await fs.cp(absolute(base, source), target, {
          recursive: true
        });
      })();
      copying[target] = current;
      return await current;
    },
    exists: async path => {
      let match = await mods();
      try {
        await match[0].access(absolute(match[1], path));
        return true;
      } catch (exn) {
        return false;
      }
    },
    glob: async pattern => {
      let match = await mods();
      let base = match[1];
      let entries;
      try {
        entries = await match[0].readdir(base, {
          withFileTypes: true,
          recursive: true
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(e => (e.parentPath + `/` + e.name).slice(base.length + 1 | 0).replace(slashes, "/")).filter(matcher(pattern)).toSorted(Primitive_string.compare);
    },
    listFiles: async dir => {
      let match = await mods();
      let entries;
      try {
        entries = await match[0].readdir(absolute(match[1], dir), {
          withFileTypes: true,
          recursive: false
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(__x => __x.name).toSorted(Primitive_string.compare);
    },
    listDirs: async dir => {
      let match = await mods();
      let entries;
      try {
        entries = await match[0].readdir(absolute(match[1], dir), {
          withFileTypes: true,
          recursive: false
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isDirectory()).map(__x => __x.name).toSorted(Primitive_string.compare);
    }
  };
}

async function run(options) {
  let inline = Stdlib_Option.getOr(options.inlineErrors, false);
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : nodeFs(undefined);
  let configs = await fs$1.glob(options.glob);
  if (configs.length === 0) {
    Schema.fail(`No config files match "` + options.glob + `"`);
  }
  let transforms = Object.assign(Object.assign({}, defaults), Stdlib_Option.getOr(options.transform, {}));
  await Promise.all(configs.toSorted(Primitive_string.compare).map(config => exec(fs$1, transforms, inline, config)));
}

async function entry(fs, glob) {
  let path = (await fs.glob(glob)).toSorted(Primitive_string.compare)[0];
  if (path !== undefined) {
    return path;
  } else {
    return Schema.fail(`No config files match "` + glob + `"`);
  }
}

async function watch(options) {
  let root = Stdlib_Option.getOr(options.root, process.cwd());
  let path = options.build;
  let rebuild = path !== undefined ? () => Dev.script(path, root) : () => run({
      glob: options.glob,
      fs: options.fs,
      transform: options.transform,
      inlineErrors: options.inlineErrors
    });
  return await Dev.watch({
    root: root,
    watch: options.watch,
    ignore: options.ignore,
    extensions: options.extensions
  }, rebuild);
}

async function dev(options) {
  let root = Stdlib_Option.getOr(options.root, process.cwd());
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : nodeFs(undefined);
  let path = options.build;
  let rebuild = path !== undefined ? () => Dev.script(path, root) : () => run({
      glob: options.glob,
      fs: options.fs,
      transform: options.transform,
      inlineErrors: Stdlib_Option.getOr(options.inlineErrors, true)
    });
  return await Dev.dev({
    root: root,
    watch: options.watch,
    ignore: options.ignore,
    extensions: options.extensions,
    serve: options.serve,
    port: options.port
  }, {
    rebuild: rebuild,
    readPort: async () => Schema.port(await fs$1.readFile(await entry(fs$1, options.glob))),
    writePort: async port => {
      let path = await entry(fs$1, options.glob);
      return await fs$1.writeFile(path, Schema.withPort(await fs$1.readFile(path), port));
    }
  });
}

export {
  run,
  makeMemoryFileSystem,
  nodeFs,
  watch,
  dev,
}
/* defaults Not a pure module */
