// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";
import * as Yaml from "yaml";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let rawGuard = ((prefix, fn) => {
  try { return fn() } catch (e) { e.message = prefix + ": " + e.message; throw e }
});

function guard(prefix, fn) {
  return rawGuard(prefix, fn);
}

let Yaml$1 = {};

function dirname(path) {
  let i = path.lastIndexOf("/");
  if (i < 0) {
    return "";
  } else {
    return path.slice(0, i);
  }
}

function join(dir, path) {
  if (dir === "" || path.startsWith("/")) {
    return path;
  } else {
    return dir + `/` + path;
  }
}

function opt(s) {
  return Sury.$res_nullableAsOption(s);
}

let scalarS = Sury.union([
  Sury.string,
  S.to(Sury.float, Sury.string),
  S.to(Sury.bool, Sury.string)
]);

let fileS = Sury.object(s => ({
  file: s.f("file", Sury.string),
  transform: s.f("transform", Sury.$res_nullableAsOption(Sury.string))
}));

let dirS = Sury.object(s => ({
  dir: s.f("dir", Sury.string),
  glob: s.f("glob", Sury.$res_nullableAsOption(Sury.string)),
  each: s.f("each", Sury.$res_nullableAsOption(Sury.string)),
  transform: s.f("transform", Sury.$res_nullableAsOption(Sury.string))
}));

let listS = Sury.object(s => ({
  list: s.f("list", Sury.string),
  each: s.f("each", Sury.string),
  join: s.f("join", Sury.$res_nullableAsOption(Sury.string)),
  template: s.f("template", Sury.$res_nullableAsOption(Sury.string))
}));

let pipeS = Sury.object(s => ({
  value: s.f("value", Sury.string),
  transform: s.f("transform", Sury.string)
}));

let varS = Sury.union([
  Sury.shape(scalarS, s => ({
    TAG: "Scalar",
    _0: s
  })),
  Sury.shape(Sury.array(scalarS), a => ({
    TAG: "Scalars",
    _0: a
  })),
  Sury.shape(dirS, d => ({
    TAG: "DirV",
    _0: d
  })),
  Sury.shape(fileS, f => ({
    TAG: "FileV",
    _0: f
  })),
  Sury.shape(listS, l => ({
    TAG: "ListV",
    _0: l
  })),
  Sury.shape(pipeS, p => ({
    TAG: "PipeV",
    _0: p
  }))
]);

let inputS = Sury.union([
  Sury.shape(Sury.string, t => ({
    TAG: "Text",
    _0: t
  })),
  Sury.object(s => ({
    TAG: "Copy",
    _0: s.f("copy", Sury.string)
  })),
  Sury.shape(dirS, d => ({
    TAG: "DirI",
    _0: d
  })),
  Sury.shape(fileS, f => ({
    TAG: "FileI",
    _0: f
  }))
]);

let buildS = Sury.object(s => ({
  vars: s.f("var", Sury.$res_nullableAsOption(Sury.dict(varS))),
  output: s.f("output", Sury.string),
  input: s.f("input", inputS)
}));

let configS = Sury.object(s => ({
  vars: s.f("var", Sury.$res_nullableAsOption(Sury.dict(varS))),
  base: s.f("base", Sury.$res_nullableAsOption(Sury.string)),
  build: s.f("build", Sury.$res_nullableAsOption(Sury.array(buildS)))
}));

let dataS = Sury.union([
  Sury.shape(scalarS, s => ({
    TAG: "One",
    _0: s
  })),
  Sury.shape(Sury.array(scalarS), a => ({
    TAG: "Many",
    _0: a
  }))
]);

let frontS = Sury.$res_nullableAsOption(Sury.dict(dataS));

function anchor(dir, v) {
  switch (v.TAG) {
    case "FileV" :
      let f = v._0;
      return {
        TAG: "FileV",
        _0: {
          file: join(dir, f.file),
          transform: f.transform
        }
      };
    case "DirV" :
      let d = v._0;
      return {
        TAG: "DirV",
        _0: {
          dir: join(dir, d.dir),
          glob: d.glob,
          each: d.each,
          transform: d.transform
        }
      };
    default:
      return v;
  }
}

function convert(path, raw) {
  let dir = dirname(path);
  return {
    vars: Stdlib_Dict.mapValues(Stdlib_Option.getOr(raw.vars, {}), extra => anchor(dir, extra)),
    base: Stdlib_Option.map(raw.base, extra => join(dir, extra)),
    build: Stdlib_Option.getOr(raw.build, []).map(b => {
      let t = b.input;
      let tmp;
      switch (t.TAG) {
        case "Text" :
          tmp = {
            TAG: "Text",
            _0: t._0
          };
          break;
        case "FileI" :
          let f = t._0;
          tmp = {
            TAG: "FileI",
            _0: {
              file: join(dir, f.file),
              transform: f.transform
            }
          };
          break;
        case "DirI" :
          let d = t._0;
          tmp = {
            TAG: "DirI",
            _0: {
              dir: join(dir, d.dir),
              glob: d.glob,
              each: d.each,
              transform: d.transform
            }
          };
          break;
        case "Copy" :
          tmp = {
            TAG: "Copy",
            _0: join(dir, t._0)
          };
          break;
      }
      return {
        vars: Stdlib_Dict.mapValues(Stdlib_Option.getOr(b.vars, {}), extra => anchor(dir, extra)),
        output: join(dir, b.output),
        input: tmp
      };
    })
  };
}

function parse(text, path) {
  return rawGuard(path, () => convert(path, S.parseOrThrow(Yaml.parse(text), configS)));
}

function front(head, at) {
  return rawGuard(at, () => Stdlib_Option.getOr(S.parseOrThrow(Yaml.parse(head), frontS), {}));
}

function port(text) {
  try {
    let v = Yaml.parseDocument(text).getIn([
      "var",
      "port"
    ]);
    if (v == null) {
      return;
    }
    let match = typeof v;
    if (match === "string") {
      return Stdlib_Int.fromString(v, undefined);
    } else if (match === "number") {
      return v;
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function withPort(text, n) {
  let doc = Yaml.parseDocument(text);
  doc.setIn([
    "var",
    "port"
  ], n);
  return doc.toString();
}

let fail = Stdlib_JsError.throwWithMessage;

export {
  fail,
  rawGuard,
  guard,
  Yaml$1 as Yaml,
  dirname,
  join,
  opt,
  scalarS,
  fileS,
  dirS,
  listS,
  pipeS,
  varS,
  inputS,
  buildS,
  configS,
  dataS,
  frontS,
  anchor,
  convert,
  parse,
  front,
  port,
  withPort,
}
/* scalarS Not a pure module */
