// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Sury from "sury";
import * as Yaml from "yaml";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

let rawGuard = ((prefix, fn) => {
  try { return fn() } catch (e) {
    const message = prefix + ": " + e.message
    try { e.message = message } catch { throw new Error(message, { cause: e }) }
    throw e
  }
});

function guard(prefix, fn) {
  return rawGuard(prefix, fn);
}

let Yaml$1 = {};

function dirname(path) {
  let i = path.lastIndexOf("/");
  if (i < 0) {
    return "";
  } else {
    return path.slice(0, i);
  }
}

function join(dir, path) {
  if (dir === "" || path.startsWith("/")) {
    return path;
  } else {
    return dir + `/` + path;
  }
}

function opt(s) {
  return Sury.$res_nullableAsOption(s);
}

let scalarS = Sury.union([
  Sury.string,
  S.to(Sury.float, Sury.string),
  S.to(Sury.bool, Sury.string)
]);

let orderS = Sury.enum([
  "asc",
  "desc"
]);

let sourceS = Sury.object(s => ({
  dir: s.f("dir", Sury.string),
  glob: s.f("glob", Sury.$res_nullableAsOption(Sury.string)),
  transform: s.f("transform", Sury.$res_nullableAsOption(Sury.string)),
  optional: s.f("optional", Sury.$res_nullableAsOption(Sury.bool)),
  order: s.f("order", Sury.$res_nullableAsOption(orderS))
}));

let treeS = Sury.recursive("Tree", treeS => Sury.union([
  Sury.shape(scalarS, s => ({
    TAG: "Str",
    _0: s
  })),
  Sury.shape(Sury.array(scalarS), a => ({
    TAG: "Strs",
    _0: a
  })),
  Sury.shape(Sury.dict(treeS), d => ({
    TAG: "Tree",
    _0: d
  }))
]));

let inputS = Sury.union([
  Sury.shape(Sury.string, t => ({
    TAG: "Text",
    _0: t
  })),
  Sury.object(s => ({
    TAG: "Copy",
    _0: s.f("copy", Sury.string)
  })),
  Sury.shape(Sury.dict(treeS), d => ({
    TAG: "Node",
    _0: d
  }))
]);

let buildS = Sury.object(s => ({
  vars: s.f("var", Sury.$res_nullableAsOption(Sury.dict(treeS))),
  pages: s.f("pages", Sury.$res_nullableAsOption(sourceS)),
  output: s.f("output", Sury.string),
  input: s.f("input", inputS)
}));

let configS = Sury.object(s => ({
  vars: s.f("var", Sury.$res_nullableAsOption(Sury.dict(treeS))),
  base: s.f("base", Sury.$res_nullableAsOption(Sury.string)),
  build: s.f("build", Sury.$res_nullableAsOption(Sury.array(buildS)))
}));

let frontS = Sury.$res_nullableAsOption(Sury.dict(treeS));

function convert(path, raw) {
  let dir = dirname(path);
  return {
    path: path,
    vars: Stdlib_Option.getOr(raw.vars, {}),
    base: Stdlib_Option.map(raw.base, extra => join(dir, extra)),
    build: Stdlib_Option.getOr(raw.build, []).map(b => {
      let c = b.input;
      let tmp;
      switch (c.TAG) {
        case "Copy" :
          tmp = {
            TAG: "Copy",
            _0: join(dir, c._0)
          };
          break;
        case "Text" :
        case "Node" :
          tmp = c;
          break;
      }
      return {
        vars: Stdlib_Option.getOr(b.vars, {}),
        pages: Stdlib_Option.map(b.pages, p => ({
          dir: join(dir, p.dir),
          glob: p.glob,
          transform: p.transform,
          optional: p.optional,
          order: p.order
        })),
        output: join(dir, b.output),
        input: tmp
      };
    })
  };
}

function parse(text, path) {
  return rawGuard(path, () => convert(path, S.parseOrThrow(Yaml.parse(text), configS)));
}

function front(head, at) {
  return rawGuard(at, () => Stdlib_Option.getOr(S.parseOrThrow(Yaml.parse(head), frontS), {}));
}

function port(text) {
  try {
    let v = Yaml.parseDocument(text).getIn([
      "var",
      "port"
    ]);
    if (v == null) {
      return;
    }
    let match = typeof v;
    if (match === "string") {
      return Stdlib_Int.fromString(v, undefined);
    } else if (match === "number") {
      return v;
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function withPort(text, n) {
  let doc = Yaml.parseDocument(text);
  doc.setIn([
    "var",
    "port"
  ], n);
  return doc.toString();
}

let fail = Stdlib_JsError.throwWithMessage;

export {
  fail,
  rawGuard,
  guard,
  Yaml$1 as Yaml,
  dirname,
  join,
  opt,
  scalarS,
  orderS,
  sourceS,
  treeS,
  inputS,
  buildS,
  configS,
  frontS,
  convert,
  parse,
  front,
  port,
  withPort,
}
/* scalarS Not a pure module */
