// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Schema from "./Schema.res.mjs";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let import_ = ((name) => import(name));

function say(message) {
  console.log(`minidoc: ` + message);
}

function absolute(base, path) {
  if (path.startsWith("/")) {
    return path;
  } else {
    return Schema.join(base, path);
  }
}

let slashes = new RegExp("\\\\", "g");

let ignored = [
  "dist",
  "node_modules",
  "lib"
];

let extensions = [
  "md",
  "markdown",
  "yml",
  "yaml",
  "html",
  "htm",
  "css",
  "svg",
  "js",
  "mjs",
  "cjs",
  "ts",
  "mts"
];

function changed(skip, exts, name) {
  let parts = name.replace(slashes, "/").split("/");
  let base = Stdlib_Option.getOr(parts.at(-1), "");
  if (parts.some(p => {
      if (p === "" || p.startsWith(".")) {
        return true;
      } else {
        return skip.includes(p);
      }
    }) || base.endsWith("~")) {
    return false;
  }
  let at = base.lastIndexOf(".");
  if (at !== -1) {
    return exts.includes(base.slice(at + 1 | 0));
  } else {
    return false;
  }
}

let attempt = (async (fn) => {
  try { await fn(); return null } catch (e) { return String((e && e.stack) || e) }
});

function looper(rebuild, built) {
  let busy = {
    contents: false
  };
  let again = {
    contents: false
  };
  let go = async () => {
    busy.contents = true;
    let started = Date.now();
    let failure = await attempt(rebuild);
    busy.contents = false;
    if (failure == null) {
      say(`built in ` + (Date.now() - started | 0).toString() + `ms`);
    } else {
      console.error(failure);
    }
    if (again.contents) {
      again.contents = false;
      return await go();
    } else {
      return built((failure == null) ? undefined : Primitive_option.some(failure));
    }
  };
  return async () => {
    if (busy.contents) {
      again.contents = true;
      return;
    } else {
      return await go();
    }
  };
}

let rawSpawn = ((spawn, bin, args, cwd) =>
  new Promise((resolve) => {
    const child = spawn(bin, args, {cwd, stdio: "inherit"})
    child.on("exit", (code) => resolve(code ?? 1))
    child.on("error", (e) => { console.error(e); resolve(1) })
  }));

async function script(path, at) {
  let cp = await import_("node:child_process");
  let code = await rawSpawn(cp.spawn, process.execPath, [path], at);
  if (code !== 0) {
    return Schema.fail(`build script ` + path + ` exited with code ` + code.toString());
  }
}

async function folder(path) {
  try {
    let fs = await import_("node:fs/promises");
    return (await fs.stat(path)).isDirectory();
  } catch (exn) {
    return false;
  }
}

async function watching(paths, skip, exts, trigger) {
  let fs = await import_("node:fs");
  let pending = {
    contents: undefined
  };
  let soon = () => {
    Stdlib_Option.forEach(pending.contents, prim => {
      clearTimeout(prim);
    });
    pending.contents = Primitive_option.some(setTimeout(() => {
      pending.contents = undefined;
      trigger();
    }, 60));
  };
  return await Promise.all(paths.map(async path => {
    let deep = await folder(path);
    return fs.watch(path, {
      recursive: deep,
      persistent: true
    }, (_event, name) => {
      if (name == null) {
        if (deep) {
          return;
        } else {
          return soon();
        }
      } else if (changed(skip, exts, name)) {
        return soon();
      } else {
        return;
      }
    });
  }));
}

async function readBytes(path) {
  let fs = await import_("node:fs/promises");
  try {
    let info = await fs.stat(path);
    if (info.isFile()) {
      return Primitive_option.some(await fs.readFile(path));
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

let types = Object.fromEntries([
  [
    "html",
    "text/html; charset=utf-8"
  ],
  [
    "htm",
    "text/html; charset=utf-8"
  ],
  [
    "css",
    "text/css; charset=utf-8"
  ],
  [
    "js",
    "text/javascript; charset=utf-8"
  ],
  [
    "mjs",
    "text/javascript; charset=utf-8"
  ],
  [
    "json",
    "application/json; charset=utf-8"
  ],
  [
    "map",
    "application/json; charset=utf-8"
  ],
  [
    "svg",
    "image/svg+xml"
  ],
  [
    "png",
    "image/png"
  ],
  [
    "jpg",
    "image/jpeg"
  ],
  [
    "jpeg",
    "image/jpeg"
  ],
  [
    "gif",
    "image/gif"
  ],
  [
    "webp",
    "image/webp"
  ],
  [
    "avif",
    "image/avif"
  ],
  [
    "ico",
    "image/x-icon"
  ],
  [
    "woff",
    "font/woff"
  ],
  [
    "woff2",
    "font/woff2"
  ],
  [
    "ttf",
    "font/ttf"
  ],
  [
    "txt",
    "text/plain; charset=utf-8"
  ],
  [
    "xml",
    "application/xml; charset=utf-8"
  ]
]);

let plain = Object.fromEntries([[
    "content-type",
    "text/plain; charset=utf-8"
  ]]);

function extension(path) {
  let at = path.lastIndexOf(".");
  if (at !== -1) {
    return path.slice(at + 1 | 0).toLowerCase();
  } else {
    return "";
  }
}

let channel = "/__minidoc";

let live = `<script>new EventSource("` + channel + `").addEventListener("message",()=>location.reload())</script>`;

function inject(html) {
  let at = html.lastIndexOf("</body>");
  if (at !== -1) {
    return html.slice(0, at) + live + html.slice(at);
  } else {
    return html + live;
  }
}

function candidates(path) {
  if (path.endsWith("/")) {
    return [path + "index.html"];
  } else if (extension(path) === "") {
    return [
      path + ".html",
      path + "/index.html"
    ];
  } else {
    return [path];
  }
}

async function serve(dir, clients, req, res) {
  let path = decodeURIComponent(req.url.split("?")[0]);
  if (path === channel) {
    res.writeHead(200, Object.fromEntries([
      [
        "content-type",
        "text/event-stream"
      ],
      [
        "cache-control",
        "no-cache"
      ],
      [
        "connection",
        "keep-alive"
      ]
    ]));
    res.write(":open\n\n");
    clients.contents = Belt_Array.concatMany([
      clients.contents,
      [res]
    ]);
    res.on("close", () => {
      clients.contents = clients.contents.filter(r => r !== res);
    });
    return;
  }
  if (path.includes("..")) {
    res.writeHead(403, plain);
    res.end("Forbidden");
    return;
  }
  let wanted = candidates(path === "/" ? "/index.html" : path);
  let first = async i => {
    let name = wanted[i];
    if (name === undefined) {
      return;
    }
    let bytes = await readBytes(absolute(dir, name.slice(1)));
    if (bytes !== undefined) {
      return [
        name,
        Primitive_option.valFromOption(bytes)
      ];
    } else {
      return await first(i + 1 | 0);
    }
  };
  let match = await first(0);
  if (match !== undefined) {
    let bytes = match[1];
    let kind = Stdlib_Option.getOr(types[extension(match[0])], "application/octet-stream");
    res.writeHead(200, Object.fromEntries([
      [
        "content-type",
        kind
      ],
      [
        "cache-control",
        "no-store"
      ]
    ]));
    if (kind.startsWith("text/html")) {
      res.end(inject(bytes.toString("utf8")));
    } else {
      res.end(bytes);
    }
    return;
  }
  res.writeHead(404, plain);
  res.end(`Not found: ` + path);
}

let rawListen = ((server, port, host) =>
  new Promise((resolve) => {
    const failed = () => {
      server.removeListener("listening", ready)
      resolve(-1)
    }
    const ready = () => {
      server.removeListener("error", failed)
      resolve(server.address().port)
    }
    server.once("error", failed)
    server.once("listening", ready)
    server.listen(port, host)
  }));

let host = "127.0.0.1";

async function watch(options, rebuild) {
  let root = Stdlib_Option.getOr(options.root, process.cwd());
  let trigger = looper(rebuild, param => {});
  await trigger();
  let watchers = await watching(Belt_Array.concatMany([
    [root],
    Stdlib_Option.getOr(options.watch, [])
  ]), Stdlib_Option.getOr(options.ignore, ignored), Stdlib_Option.getOr(options.extensions, extensions), trigger);
  say(`watching ` + root);
  return {
    stop: () => {
      watchers.forEach(prim => {
        prim.close();
      });
    }
  };
}

async function dev(options, hooks) {
  let root = Stdlib_Option.getOr(options.root, process.cwd());
  let dir = absolute(root, Stdlib_Option.getOr(options.serve, "dist"));
  let clients = {
    contents: []
  };
  let http = await import_("node:http");
  let server = http.createServer((req, res) => {
    serve(dir, clients, req, res);
  });
  let port = options.port;
  let remembered = port !== undefined ? port : await hooks.readPort();
  let wanted = Stdlib_Option.getOr(remembered, 0);
  let port$1 = await rawListen(server, wanted, host);
  let port$2 = port$1 !== -1 ? port$1 : (wanted !== 0 ? say(`port ` + wanted.toString() + ` is taken — drawing another`) : undefined, await rawListen(server, 0, host));
  if (port$2 < 0) {
    Schema.fail(`dev server could not listen on ` + host);
  }
  let match = options.port;
  if (match !== undefined) {
    
  } else if (remembered !== undefined) {
    if (remembered === port$2) {
      
    } else {
      await hooks.writePort(port$2);
    }
  } else {
    await hooks.writePort(port$2);
  }
  let trigger = looper(hooks.rebuild, param => {
    clients.contents.forEach(r => {
      r.write("data: reload\n\n");
    });
  });
  await trigger();
  let watchers = await watching(Belt_Array.concatMany([
    [root],
    Stdlib_Option.getOr(options.watch, [])
  ]), Stdlib_Option.getOr(options.ignore, ignored), Stdlib_Option.getOr(options.extensions, extensions), trigger);
  say(`http://` + host + `:` + port$2.toString() + ` — watching ` + root);
  return {
    port: port$2,
    stop: () => {
      watchers.forEach(prim => {
        prim.close();
      });
      clients.contents.forEach(r => {
        r.end("");
      });
      server.close();
    }
  };
}

export {
  import_,
  say,
  absolute,
  slashes,
  ignored,
  extensions,
  changed,
  attempt,
  looper,
  rawSpawn,
  script,
  folder,
  watching,
  readBytes,
  types,
  plain,
  extension,
  channel,
  live,
  inject,
  candidates,
  serve,
  rawListen,
  host,
  watch,
  dev,
}
/* slashes Not a pure module */
