// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.res.mjs";
import * as Schema from "./Schema.res.mjs";
import * as Marked from "marked";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let reference = new RegExp("\\{\\{\\s*([A-Za-z_][A-Za-z0-9_.-]*)\\s*\\}\\}", "g");

let depth = {
  contents: 0
};

function over(parent, own) {
  return Object.assign(Object.assign({}, parent), own);
}

function data(front) {
  return Stdlib_Dict.mapValues(front, d => {
    if (d.TAG === "One") {
      return {
        TAG: "T",
        _0: d._0
      };
    } else {
      return {
        TAG: "L",
        _0: d._0
      };
    }
  });
}

function make(lvars) {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      lvars: lvars,
      vars: Stdlib_Dict.mapValues(lvars, lv => derived(self => $$eval(lv, self))),
      get: derived(self => (name => self.vars[name]))
    };
  });
}

function sub(self, extra) {
  return make(Object.assign(Object.assign({}, self.lvars), extra));
}

function $$eval(lv, self) {
  switch (lv.TAG) {
    case "T" :
      return {
        TAG: "One",
        _0: render(lv._0, self.get)
      };
    case "L" :
      return {
        TAG: "Many",
        _0: lv._0.map(__x => render(__x, self.get))
      };
    case "V" :
      return lv._0;
    case "F" :
      let c = lv._0;
      return {
        TAG: "One",
        _0: c.transform(render(c.body, sub(self, data(c.front)).get))
      };
    case "D" :
      let each = lv._1;
      return {
        TAG: "One",
        _0: lv._0.map(c => {
          let front = sub(self, data(c.front));
          let body = c.transform(render(c.body, front.get));
          return render(each, sub(front, Object.fromEntries([[
              "body",
              {
                TAG: "V",
                _0: {
                  TAG: "One",
                  _0: body
                }
              }
            ]])).get);
        }).join("\n")
      };
    case "R" :
      let l = lv._0;
      let match = self.get(l.list);
      if (match === undefined) {
        return {
          TAG: "One",
          _0: ""
        };
      }
      if (match.TAG === "One") {
        return {
          TAG: "One",
          _0: ""
        };
      }
      let items = match._0;
      if (items.length === 0) {
        return {
          TAG: "One",
          _0: ""
        };
      }
      let one = (name, value, template) => render(template, sub(self, Object.fromEntries([[
          name,
          {
            TAG: "V",
            _0: {
              TAG: "One",
              _0: value
            }
          }
        ]])).get);
      let body = items.map(item => one("item", item, l.each)).join(Stdlib_Option.getOr(l.join, ""));
      let template = l.template;
      return {
        TAG: "One",
        _0: template !== undefined ? one("body", body, template) : body
      };
    case "P" :
      return {
        TAG: "One",
        _0: lv._1(render(lv._0, self.get))
      };
  }
}

function render(template, get) {
  if (depth.contents > 8) {
    return "[cycle]";
  }
  depth.contents = depth.contents + 1 | 0;
  let out = template.replace(reference, (ref, name, param, param$1) => {
    let match = get(name);
    if (match !== undefined) {
      if (match.TAG === "One") {
        return match._0;
      } else {
        return match._0.join("");
      }
    } else {
      return Schema.fail(`Undefined variable ` + ref);
    }
  });
  depth.contents = depth.contents - 1 | 0;
  return out;
}

let Md = {};

let defaults = Object.fromEntries([
  [
    "md",
    text => Marked.marked.parse(text, {
      async: false
    })
  ],
  [
    "none",
    text => text
  ]
]);

let special = new RegExp("[.*+?^${}()|[\\]\\\\]", "g");

function matcher(glob) {
  let source = glob.split("*").map(part => part.replace(special, "\\$&")).join("[^/]*");
  let re = new RegExp(`^` + source + `$`);
  return name => re.test(name);
}

let matter = new RegExp("^---\\n(?:([\\s\\S]*?)\\n)?---(?:\\n|$)");

function split(text, at) {
  if (!text.startsWith("---\n")) {
    return {
      front: {},
      body: text
    };
  }
  let m = matter.exec(text);
  if (m == null) {
    return Schema.fail(at + `: unterminated frontmatter`);
  }
  let match = m.slice(1)[0];
  let vars;
  if (match !== undefined) {
    let head = Primitive_option.valFromOption(match);
    vars = head !== undefined ? Schema.front(head, at) : ({});
  } else {
    vars = {};
  }
  return {
    front: vars,
    body: text.slice(m[0].length)
  };
}

function infer(path) {
  if (path.endsWith(".md") || path.endsWith(".markdown")) {
    return "md";
  } else if (path.endsWith(".html") || path.endsWith(".htm")) {
    return "none";
  } else {
    return;
  }
}

async function seq(xs, i, fn) {
  if (i < xs.length) {
    await fn(xs[i]);
    return await seq(xs, i + 1 | 0, fn);
  }
}

function strs(vars, parent) {
  let get = name => {
    let match = vars[name];
    if (match !== undefined && match.TAG === "Scalar") {
      return {
        TAG: "One",
        _0: render(match._0, get)
      };
    } else {
      return parent(name);
    }
  };
  return get;
}

async function load(fs, transforms, pget, vars) {
  let out = {};
  let $$exports = {};
  let content = async (path, explicit) => {
    let match = split(await fs.readFile(path), path);
    let name = Stdlib_Option.getOr(Stdlib_Option.orElse(explicit, infer(path)), "none");
    let transform = transforms[name];
    if (transform !== undefined) {
      return {
        body: match.body,
        transform: transform,
        front: match.front
      };
    } else {
      return Schema.fail(`unknown transform "` + name + `"`);
    }
  };
  await seq(Object.entries(vars), 0, async param => {
    let v = param[1];
    let name = param[0];
    switch (v.TAG) {
      case "Scalar" :
        out[name] = {
          TAG: "T",
          _0: v._0
        };
        return;
      case "Scalars" :
        out[name] = {
          TAG: "L",
          _0: v._0
        };
        return;
      case "FileV" :
        let f = v._0;
        let c = await content(render(f.file, pget), f.transform);
        Object.entries(data(c.front)).forEach(param => {
          $$exports[param[0]] = param[1];
        });
        out[name] = {
          TAG: "F",
          _0: c
        };
        return;
      case "DirV" :
        let d = v._0;
        let dir = render(d.dir, pget);
        let names = (await fs.listFiles(dir)).filter(matcher(Stdlib_Option.getOr(d.glob, "*.md")));
        let items = await Promise.all(names.map(n => content(Schema.join(dir, n), d.transform)));
        out[name] = {
          TAG: "D",
          _0: items,
          _1: Stdlib_Option.getOr(d.each, "{{body}}")
        };
        return;
      case "ListV" :
        out[name] = {
          TAG: "R",
          _0: v._0
        };
        return;
      case "PipeV" :
        let p = v._0;
        let t = transforms[p.transform];
        if (t !== undefined) {
          out[name] = {
            TAG: "P",
            _0: p.value,
            _1: t
          };
          return;
        } else {
          return Schema.fail(`unknown transform "` + p.transform + `"`);
        }
    }
  });
  return [
    out,
    $$exports
  ];
}

async function chain(fs, path, visited) {
  if (visited.includes(path)) {
    Schema.fail(`Base config cycle: ` + path);
  }
  let config = Schema.parse(await fs.readFile(path), path);
  let base = config.base;
  if (base !== undefined) {
    return (await chain(fs, base, Belt_Array.concatMany([
      visited,
      [path]
    ]))).concat([config]);
  } else {
    return [config];
  }
}

async function exec(fs, transforms, entry) {
  let configs = await chain(fs, entry, []);
  let pget = Stdlib_Array.reduce(configs, param => {}, (parent, c) => strs(c.vars, parent));
  let grow = async (acc, i) => {
    if (i >= configs.length) {
      return acc;
    }
    let match = await load(fs, transforms, pget, configs[i].vars);
    let parent = Object.assign(Object.assign({}, acc), match[1]);
    return await grow(Object.assign(Object.assign({}, parent), match[0]), i + 1 | 0);
  };
  let shared = await grow({}, 0);
  let entry$1 = configs[configs.length - 1 | 0];
  return await Promise.all(entry$1.build.map(async b => {
    let bpget = strs(b.vars, pget);
    let match = await load(fs, transforms, bpget, b.vars);
    let $$exports = match[1];
    let own = match[0];
    let layer = front => {
      let parent = Object.assign(Object.assign({}, front), shared);
      let parent$1 = Object.assign(Object.assign({}, parent), $$exports);
      return make(Object.assign(Object.assign({}, parent$1), own));
    };
    let path = b.input;
    if (path.TAG === "Copy") {
      return await fs.copy(render(path._0, bpget), render(b.output, layer({}).get));
    }
    let match$1;
    switch (path.TAG) {
      case "Text" :
        match$1 = [
          {
            TAG: "T",
            _0: path._0
          },
          layer({})
        ];
        break;
      case "FileI" :
        let f = path._0;
        let match$2 = split(await fs.readFile(render(f.file, bpget)), f.file);
        let front = match$2.front;
        let name = Stdlib_Option.getOr(Stdlib_Option.orElse(f.transform, infer(f.file)), "none");
        let transform = Stdlib_Option.getOr(transforms[name], text => text);
        match$1 = [
          {
            TAG: "F",
            _0: {
              body: match$2.body,
              transform: transform,
              front: front
            }
          },
          layer(data(front))
        ];
        break;
      case "DirI" :
        let d = path._0;
        let dir = render(d.dir, bpget);
        let names = (await fs.listFiles(dir)).filter(matcher(Stdlib_Option.getOr(d.glob, "*.md")));
        let items = await Promise.all(names.map(async n => {
          let match = split(await fs.readFile(Schema.join(dir, n)), n);
          let name = Stdlib_Option.getOr(Stdlib_Option.orElse(d.transform, infer(n)), "none");
          return {
            body: match.body,
            transform: Stdlib_Option.getOr(transforms[name], text => text),
            front: match.front
          };
        }));
        match$1 = [
          {
            TAG: "D",
            _0: items,
            _1: Stdlib_Option.getOr(d.each, "{{body}}")
          },
          layer({})
        ];
        break;
      case "Copy" :
        match$1 = [
          {
            TAG: "T",
            _0: ""
          },
          layer({})
        ];
        break;
    }
    let bctx = match$1[1];
    let s = $$eval(match$1[0], bctx);
    let out;
    out = s.TAG === "One" ? s._0 : s._0.join("");
    return await fs.writeFile(render(b.output, bctx.get), out);
  }));
}

async function run(options) {
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : Schema.fail("MinidocTilia: fs is required");
  let transforms = Object.assign(Object.assign({}, defaults), Stdlib_Option.getOr(options.transform, {}));
  let configs = await fs$1.glob(options.glob);
  if (configs.length === 0) {
    Schema.fail(`No config files match "` + options.glob + `"`);
  }
  await Promise.all(configs.map(config => exec(fs$1, transforms, config)));
}

export {
  reference,
  depth,
  over,
  data,
  make,
  sub,
  $$eval,
  render,
  Md,
  defaults,
  special,
  matcher,
  matter,
  split,
  infer,
  seq,
  strs,
  load,
  chain,
  exec,
  run,
}
/* reference Not a pure module */
