// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.res.mjs";
import * as Schema from "./Schema.res.mjs";
import * as Marked from "marked";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

let defaults = Object.fromEntries([
  [
    "md",
    text => Marked.marked.parse(text, {
      async: false
    })
  ],
  [
    "none",
    text => text
  ]
]);

let reference = new RegExp("\\{\\{\\s*(`?)([A-Za-z_][A-Za-z0-9_.-]*)\\1\\s*\\}\\}", "g");

let backtick = new RegExp("`", "g");

let stack = {
  contents: []
};

let rawSite = ((at, fn) => {
  try { return fn() } catch (e) {
    if (/^Undefined variable/.test(e.message) && !e.message.includes(" in ")) {
      e.message += " in " + at
    } else if (e.message.startsWith("Variable cycle:")) {
      e.message = "Variable cycle in " + at + ":" + e.message.slice(15)
    }
    throw e
  }
});

function data(front) {
  return Stdlib_Dict.mapValues(front, d => {
    if (d.TAG === "One") {
      return {
        TAG: "T",
        _0: d._0
      };
    } else {
      return {
        TAG: "L",
        _0: d._0
      };
    }
  });
}

function make(lvars) {
  return Tilia.carve(param => {
    let derived = param.derived;
    return {
      lvars: lvars,
      vars: Stdlib_Dict.mapValues(lvars, lv => derived(self => $$eval(lv, self))),
      get: derived(self => (name => self.vars[name]))
    };
  });
}

function sub(self, extra) {
  return make(Object.assign(Object.assign({}, self.lvars), extra));
}

function $$eval(lv, self) {
  switch (lv.TAG) {
    case "T" :
      return {
        TAG: "One",
        _0: render(lv._0, self.get)
      };
    case "L" :
      return {
        TAG: "Many",
        _0: lv._0.map(__x => render(__x, self.get))
      };
    case "V" :
      return lv._0;
    case "F" :
      let c = lv._0;
      return {
        TAG: "One",
        _0: c.transform(rawSite(c.at, () => render(c.body, sub(self, data(c.front)).get)))
      };
    case "D" :
      let each = lv._1;
      let items = lv._0;
      return {
        TAG: "One",
        _0: rawSite(lv._2, () => items.map(c => {
          let front = sub(self, data(c.front));
          let body = c.transform(rawSite(c.at, () => render(c.body, front.get)));
          return render(each, sub(front, Object.fromEntries([[
              "body",
              {
                TAG: "V",
                _0: {
                  TAG: "One",
                  _0: body
                }
              }
            ]])).get);
        }).join("\n"))
      };
    case "R" :
      let l = lv._0;
      let match = self.get(l.list);
      if (match === undefined) {
        return Schema.fail(`Undefined variable {{` + l.list + `}}`);
      }
      if (match.TAG === "One") {
        return Schema.fail(lv._1 + `: "` + l.list + `" must resolve to a scalar list`);
      }
      let items$1 = match._0;
      if (items$1.length === 0) {
        return {
          TAG: "One",
          _0: ""
        };
      }
      let one = (name, value, template) => render(template, sub(self, Object.fromEntries([[
          name,
          {
            TAG: "V",
            _0: {
              TAG: "One",
              _0: value
            }
          }
        ]])).get);
      let body = items$1.map(item => one("item", item, l.each)).join(Stdlib_Option.getOr(l.join, ""));
      let template = l.template;
      return {
        TAG: "One",
        _0: template !== undefined ? one("body", body, template) : body
      };
    case "P" :
      let value = lv._0;
      return {
        TAG: "One",
        _0: lv._1(rawSite(lv._2, () => render(value, self.get)))
      };
  }
}

function render(template, get) {
  return template.replace(reference, (ref, quote, name, param, param$1) => {
    if (quote !== "") {
      return ref.replace(backtick, "");
    }
    let active = stack.contents;
    if (active.includes(name)) {
      let from = active.indexOf(name);
      Schema.fail(`Variable cycle: ` + Belt_Array.concatMany([
        active.slice(from),
        [name]
      ]).join(" -> "));
    }
    stack.contents = Belt_Array.concatMany([
      active,
      [name]
    ]);
    let match = get(name);
    let out = match !== undefined ? (
        match.TAG === "One" ? match._0 : match._0.join("")
      ) : Schema.fail(`Undefined variable ` + ref);
    stack.contents = active;
    return out;
  });
}

function top(at, fn) {
  stack.contents = [];
  return rawSite(at, fn);
}

let special = new RegExp("[.*+?^${}()|[\\]\\\\]", "g");

let slashes = new RegExp("\\\\", "g");

function matcher(glob) {
  let build = (_i, _out) => {
    while (true) {
      let out = _out;
      let i = _i;
      if (i >= glob.length) {
        return out;
      }
      if (glob.charAt(i) !== "*") {
        _out = out + glob.charAt(i).replace(special, "\\$&");
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 1 | 0) !== "*") {
        _out = out + "[^/]*";
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 2 | 0) === "/") {
        _out = out + "(?:.*/)?";
        _i = i + 3 | 0;
        continue;
      }
      _out = out + ".*";
      _i = i + 2 | 0;
      continue;
    };
  };
  let re = new RegExp(`^` + build(0, "") + `$`);
  return name => re.test(name.replace(slashes, "/"));
}

let matter = new RegExp("^---\\n(?:([\\s\\S]*?)\\n)?---(?:\\n|$)");

function split(text, at) {
  if (!text.startsWith("---\n")) {
    return {
      front: {},
      body: text
    };
  }
  let m = matter.exec(text);
  if (m == null) {
    return Schema.fail(at + `: unterminated frontmatter (missing closing "---" line)`);
  }
  let match = m.slice(1)[0];
  let vars;
  if (match !== undefined) {
    let head = Primitive_option.valFromOption(match);
    vars = head !== undefined ? Schema.front(head, at) : ({});
  } else {
    vars = {};
  }
  return {
    front: vars,
    body: text.slice(m[0].length)
  };
}

function infer(path) {
  if (path.endsWith(".md") || path.endsWith(".markdown")) {
    return "md";
  } else if (path.endsWith(".html") || path.endsWith(".htm")) {
    return "none";
  } else {
    return;
  }
}

async function seq(xs, i, fn) {
  if (i < xs.length) {
    await fn(xs[i]);
    return await seq(xs, i + 1 | 0, fn);
  }
}

function strs(vars, parent) {
  let get = name => {
    let match = vars[name];
    if (match !== undefined && match.TAG === "Scalar") {
      return {
        TAG: "One",
        _0: render(match._0, get)
      };
    } else {
      return parent(name);
    }
  };
  return get;
}

async function load(fs, transforms, pget, label, vars) {
  let named = (name, at) => {
    let t = transforms[name];
    if (t !== undefined) {
      return t;
    } else {
      return Schema.fail(at + `: unknown transform "` + name + `" (available: ` + Object.keys(transforms).join(", ") + `)`);
    }
  };
  let content = async (path, explicit, at) => {
    if (!await fs.exists(path)) {
      Schema.fail(`Content file not found: ` + path + ` (declared at ` + at + `)`);
    }
    let match = split(await fs.readFile(path), path);
    let name = Stdlib_Option.orElse(explicit, infer(path));
    let name$1 = name !== undefined ? name : Schema.fail(at + `: cannot infer a transform for ` + path + ` — set "transform" (available: ` + Object.keys(transforms).join(", ") + `)`);
    return {
      body: match.body,
      transform: named(name$1, at),
      front: match.front,
      at: `file ` + path
    };
  };
  let out = {};
  let $$exports = {};
  let owners = {};
  await seq(Object.entries(vars), 0, async param => {
    let v = param[1];
    let name = param[0];
    let at = label + `.` + name;
    switch (v.TAG) {
      case "Scalar" :
        out[name] = {
          TAG: "T",
          _0: v._0
        };
        return;
      case "Scalars" :
        out[name] = {
          TAG: "L",
          _0: v._0
        };
        return;
      case "FileV" :
        let f = v._0;
        let path = top(at + ` file`, () => render(f.file, pget));
        let c = await content(path, f.transform, at);
        Object.entries(data(c.front)).forEach(param => {
          let fname = param[0];
          let owner = owners[fname];
          if (owner !== undefined && owner !== path) {
            Schema.fail(`Frontmatter conflict in ` + label + `: "` + fname + `" defined by both ` + owner + ` and ` + path);
          }
          owners[fname] = path;
          $$exports[fname] = param[1];
        });
        out[name] = {
          TAG: "F",
          _0: c
        };
        return;
      case "DirV" :
        let d = v._0;
        let dir = top(at + ` dir`, () => render(d.dir, pget));
        let glob = Stdlib_Option.getOr(d.glob, "*.md");
        let names = (await fs.listFiles(dir)).filter(matcher(glob));
        if (names.length === 0) {
          Schema.fail(`No files matching "` + glob + `" in ` + dir + ` (declared at ` + at + `)`);
        }
        let items = await Promise.all(names.map(n => content(Schema.join(dir, n), d.transform, at)));
        out[name] = {
          TAG: "D",
          _0: items,
          _1: Stdlib_Option.getOr(d.each, "{{body}}"),
          _2: `dir ` + dir + ` (` + at + `)`
        };
        return;
      case "ListV" :
        out[name] = {
          TAG: "R",
          _0: v._0,
          _1: at
        };
        return;
      case "PipeV" :
        let p = v._0;
        out[name] = {
          TAG: "P",
          _0: p.value,
          _1: named(p.transform, at),
          _2: at
        };
        return;
    }
  });
  return [
    out,
    $$exports
  ];
}

async function chain(fs, path, visited, from) {
  if (visited.includes(path)) {
    Schema.fail(`Base config cycle: ` + Belt_Array.concatMany([
      visited,
      [path]
    ]).join(" -> "));
  }
  if (!await fs.exists(path)) {
    Schema.fail(`Config not found: ` + path + (
      from === "" ? "" : ` (base of ` + from + `)`
    ));
  }
  let config = Schema.parse(await fs.readFile(path), path);
  let base = config.base;
  if (base !== undefined) {
    return (await chain(fs, base, Belt_Array.concatMany([
      visited,
      [path]
    ]), path)).concat([config]);
  } else {
    return [config];
  }
}

async function exec(fs, transforms, entry) {
  let configs = await chain(fs, entry, [], "");
  let pget = Stdlib_Array.reduce(configs, param => {}, (parent, c) => strs(c.vars, parent));
  let grow = async (acc, i) => {
    if (i >= configs.length) {
      return acc;
    }
    let match = await load(fs, transforms, pget, `var (` + entry + `)`, configs[i].vars);
    let parent = Object.assign(Object.assign({}, acc), match[1]);
    return await grow(Object.assign(Object.assign({}, parent), match[0]), i + 1 | 0);
  };
  let shared = await grow({}, 0);
  let last = configs[configs.length - 1 | 0];
  return await Promise.all(last.build.map(async (b, i) => {
    let at = `build[` + i.toString() + `]`;
    let bpget = strs(b.vars, pget);
    let match = await load(fs, transforms, bpget, at + `.var`, b.vars);
    let $$exports = match[1];
    let own = match[0];
    let layer = front => {
      let parent = Object.assign(Object.assign({}, front), shared);
      let parent$1 = Object.assign(Object.assign({}, parent), $$exports);
      return make(Object.assign(Object.assign({}, parent$1), own));
    };
    let path = b.input;
    if (path.TAG === "Copy") {
      let path$1 = path._0;
      let source = top(at + ` input copy`, () => render(path$1, bpget));
      if (!await fs.exists(source)) {
        Schema.fail(`Copy source not found: ` + source + ` (declared at ` + at + ` input)`);
      }
      return await fs.copy(source, top(at + ` output`, () => render(b.output, layer({}).get)));
    }
    let match$1;
    switch (path.TAG) {
      case "Text" :
        match$1 = [
          {
            TAG: "T",
            _0: path._0
          },
          layer({})
        ];
        break;
      case "FileI" :
        let f = path._0;
        let path$2 = top(at + ` input file`, () => render(f.file, bpget));
        let c = await load(fs, transforms, bpget, at, Object.fromEntries([[
            "input",
            {
              TAG: "FileV",
              _0: {
                file: path$2,
                transform: f.transform
              }
            }
          ]]));
        let match$2 = c[0]["input"];
        if (match$2 !== undefined) {
          if (match$2.TAG === "F") {
            let c$1 = match$2._0;
            match$1 = [
              {
                TAG: "F",
                _0: c$1
              },
              layer(data(c$1.front))
            ];
          } else {
            match$1 = [
              {
                TAG: "T",
                _0: ""
              },
              layer({})
            ];
          }
        } else {
          match$1 = [
            {
              TAG: "T",
              _0: ""
            },
            layer({})
          ];
        }
        break;
      case "DirI" :
        let match$3 = await load(fs, transforms, bpget, at, Object.fromEntries([[
            "input",
            {
              TAG: "DirV",
              _0: path._0
            }
          ]]));
        let match$4 = match$3[0]["input"];
        match$1 = match$4 !== undefined ? (
            match$4.TAG === "D" ? [
                {
                  TAG: "D",
                  _0: match$4._0,
                  _1: match$4._1,
                  _2: match$4._2
                },
                layer({})
              ] : [
                {
                  TAG: "T",
                  _0: ""
                },
                layer({})
              ]
          ) : [
            {
              TAG: "T",
              _0: ""
            },
            layer({})
          ];
        break;
      case "Copy" :
        match$1 = [
          {
            TAG: "T",
            _0: ""
          },
          layer({})
        ];
        break;
    }
    let bctx = match$1[1];
    let lv = match$1[0];
    let s = top(at + ` input`, () => $$eval(lv, bctx));
    let out;
    out = s.TAG === "One" ? s._0 : s._0.join("");
    return await fs.writeFile(top(at + ` output`, () => render(b.output, bctx.get)), out);
  }));
}

function makeMemoryFileSystem(seed) {
  let files = Object.assign({}, Stdlib_Option.getOr(seed, {}));
  let sorted = keys => keys.toSorted(Primitive_string.compare);
  return {
    readFile: async path => {
      let content = files[path];
      if (content !== undefined) {
        return content;
      } else {
        return Schema.fail(`File not found: ` + path);
      }
    },
    writeFile: async (path, content) => {
      files[path] = content;
    },
    copy: async (source, output) => {
      let content = files[source];
      if (content !== undefined) {
        files[output] = content;
        return;
      }
      let prefix = source + `/`;
      let hits = Object.entries(files).filter(param => param[0].startsWith(prefix));
      if (hits.length === 0) {
        Schema.fail(`File not found: ` + source);
      }
      hits.forEach(param => {
        files[output + `/` + param[0].slice(prefix.length)] = param[1];
      });
    },
    exists: async path => {
      let match = files[path];
      if (match !== undefined) {
        return true;
      } else {
        return Object.keys(files).some(f => f.startsWith(path + `/`));
      }
    },
    glob: async pattern => sorted(Object.keys(files).filter(matcher(pattern))),
    listFiles: async dir => {
      let prefix = dir === "" ? "" : dir + `/`;
      return sorted(Object.keys(files).filter(p => {
        if (p.startsWith(prefix)) {
          return !p.slice(prefix.length).includes("/");
        } else {
          return false;
        }
      }).map(p => p.slice(prefix.length)));
    }
  };
}

let import_ = ((name) => import(name));

function nodeFs(root) {
  let cache = {
    contents: undefined
  };
  let mods = () => {
    let loaded = cache.contents;
    if (loaded !== undefined) {
      return loaded;
    }
    let loaded$1 = (async () => {
      let fs = await import_("node:fs/promises");
      let base;
      if (root !== undefined) {
        if (typeof root === "string") {
          base = root.startsWith("/") ? root : Schema.join(process.cwd(), root);
        } else {
          let url = await import_("node:url");
          base = url.fileURLToPath(root);
        }
      } else {
        base = process.cwd();
      }
      return [
        fs,
        base
      ];
    })();
    cache.contents = loaded$1;
    return loaded$1;
  };
  let absolute = (base, path) => {
    if (path.startsWith("/")) {
      return path;
    } else {
      return Schema.join(base, path);
    }
  };
  return {
    readFile: async path => {
      let match = await mods();
      return await match[0].readFile(absolute(match[1], path), "utf8");
    },
    writeFile: async (path, content) => {
      let match = await mods();
      let fs = match[0];
      let file = absolute(match[1], path);
      await fs.mkdir(Schema.dirname(file), {
        recursive: true
      });
      return await fs.writeFile(file, content, "utf8");
    },
    copy: async (source, output) => {
      let match = await mods();
      let base = match[1];
      let fs = match[0];
      let target = absolute(base, output);
      await fs.mkdir(Schema.dirname(target), {
        recursive: true
      });
      return await fs.cp(absolute(base, source), target, {
        recursive: true
      });
    },
    exists: async path => {
      let match = await mods();
      try {
        await match[0].access(absolute(match[1], path));
        return true;
      } catch (exn) {
        return false;
      }
    },
    glob: async pattern => {
      let match = await mods();
      let base = match[1];
      let entries;
      try {
        entries = await match[0].readdir(base, {
          withFileTypes: true,
          recursive: true
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(e => (e.parentPath + `/` + e.name).slice(base.length + 1 | 0).replace(slashes, "/")).filter(matcher(pattern)).toSorted(Primitive_string.compare);
    },
    listFiles: async dir => {
      let match = await mods();
      let entries;
      try {
        entries = await match[0].readdir(absolute(match[1], dir), {
          withFileTypes: true,
          recursive: false
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(__x => __x.name).toSorted(Primitive_string.compare);
    }
  };
}

async function run(options) {
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : nodeFs(undefined);
  let configs = await fs$1.glob(options.glob);
  if (configs.length === 0) {
    Schema.fail(`No config files match "` + options.glob + `"`);
  }
  let transforms = Object.assign(Object.assign({}, defaults), Stdlib_Option.getOr(options.transform, {}));
  await Promise.all(configs.toSorted(Primitive_string.compare).map(config => exec(fs$1, transforms, config)));
}

export {
  run,
  makeMemoryFileSystem,
  nodeFs,
}
/* defaults Not a pure module */
