// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Schema from "./Schema.res.mjs";
import * as Marked from "marked";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

async function seq(xs, i, fn) {
  if (i < xs.length) {
    await fn(xs[i]);
    return await seq(xs, i + 1 | 0, fn);
  }
}

let special = new RegExp("[.*+?^${}()|[\\]\\\\]", "g");

let slashes = new RegExp("\\\\", "g");

function matcher(glob) {
  let build = (_i, _out) => {
    while (true) {
      let out = _out;
      let i = _i;
      if (i >= glob.length) {
        return out;
      }
      if (glob.charAt(i) !== "*") {
        _out = out + glob.charAt(i).replace(special, "\\$&");
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 1 | 0) !== "*") {
        _out = out + "[^/]*";
        _i = i + 1 | 0;
        continue;
      }
      if (glob.charAt(i + 2 | 0) === "/") {
        _out = out + "(?:.*/)?";
        _i = i + 3 | 0;
        continue;
      }
      _out = out + ".*";
      _i = i + 2 | 0;
      continue;
    };
  };
  let re = new RegExp(`^` + build(0, "") + `$`);
  return name => re.test(name.replace(slashes, "/"));
}

let matter = new RegExp("^---\\n(?:([\\s\\S]*?)\\n)?---(?:\\n|$)");

let reference = new RegExp("\\{\\{\\s*([A-Za-z_][A-Za-z0-9_.-]*)\\s*\\}\\}", "g");

function labels(scopes) {
  let all = scopes.map(s => s.label).join(", ");
  if (all === "") {
    return "no scopes";
  } else {
    return all;
  }
}

function look(scopes, name) {
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= scopes.length) {
      return;
    }
    let v = scopes[i].vars[name];
    if (v !== undefined) {
      return v;
    }
    _i = i + 1 | 0;
    continue;
  };
}

function expand(text, scopes, active, at) {
  return text.replace(reference, (ref, name, param, param$1) => {
    let seen = active.indexOf(name);
    if (seen >= 0) {
      return Schema.fail(`Variable cycle in ` + at + `: ` + Belt_Array.concatMany([
        active.slice(seen),
        [name]
      ]).join(" -> "));
    }
    let v = look(scopes, name);
    if (v !== undefined) {
      return grow(v, scopes, Belt_Array.concatMany([
        active,
        [name]
      ]), at);
    } else {
      return Schema.fail(`Undefined variable ` + ref + ` in ` + at + ` (searched: ` + labels(scopes) + `)`);
    }
  });
}

function grow(v, scopes, active, at) {
  switch (v.TAG) {
    case "Str" :
      return expand(v._0, scopes, active, at);
    case "Items" :
      return v._0.map(item => expand(item, scopes, active, at)).join("");
    case "File" :
      let f = v._0;
      return f.transform(expand(f.body, Belt_Array.concatMany([
        [f.front],
        scopes
      ]), active, f.at));
    case "Folder" :
      let f$1 = v._0;
      return f$1.items.map(item => expand(f$1.each, Belt_Array.concatMany([
        [
          item.front,
          {
            label: f$1.at,
            vars: Object.fromEntries([[
                "body",
                {
                  TAG: "File",
                  _0: item
                }
              ]])
          }
        ],
        scopes
      ]), active, f$1.at)).join("\n");
    case "Loop" :
      let l = v._0;
      let match = look(scopes, l.source);
      if (match === undefined) {
        return Schema.fail(`Undefined list "` + l.source + `" in ` + l.at + ` (searched: ` + labels(scopes) + `)`);
      }
      if (match.TAG !== "Items") {
        return Schema.fail(l.at + `: "` + l.source + `" must resolve to a scalar list`);
      }
      let items = match._0;
      if (items.length === 0) {
        return "";
      }
      let body = items.map(item => expand(l.each, Belt_Array.concatMany([
        [{
            label: l.at + ` item`,
            vars: Object.fromEntries([[
                "item",
                {
                  TAG: "Str",
                  _0: item
                }
              ]])
          }],
        scopes
      ]), active, l.at)).join(l.join);
      let template = l.template;
      if (template !== undefined) {
        return expand(template, Belt_Array.concatMany([
          [{
              label: l.at + ` template`,
              vars: Object.fromEntries([[
                  "body",
                  {
                    TAG: "Str",
                    _0: body
                  }
                ]])
            }],
          scopes
        ]), active, l.at);
      } else {
        return body;
      }
    case "Piped" :
      let p = v._0;
      return p.transform(expand(p.value, scopes, active, p.at));
  }
}

let defaults = Object.fromEntries([
  [
    "md",
    text => Marked.marked.parse(text, {
      async: false
    })
  ],
  [
    "none",
    text => text
  ]
]);

function makeMemoryFileSystem(seed) {
  let files = Object.assign({}, Stdlib_Option.getOr(seed, {}));
  let sorted = keys => keys.toSorted(Primitive_string.compare);
  return {
    readFile: async path => {
      let content = files[path];
      if (content !== undefined) {
        return content;
      } else {
        return Schema.fail(`File not found: ` + path);
      }
    },
    writeFile: async (path, content) => {
      files[path] = content;
    },
    copy: async (source, output) => {
      let content = files[source];
      if (content !== undefined) {
        files[output] = content;
        return;
      }
      let prefix = source + `/`;
      let hits = Object.entries(files).filter(param => param[0].startsWith(prefix));
      if (hits.length === 0) {
        Schema.fail(`File not found: ` + source);
      }
      hits.forEach(param => {
        files[output + `/` + param[0].slice(prefix.length)] = param[1];
      });
    },
    exists: async path => {
      let match = files[path];
      if (match !== undefined) {
        return true;
      } else {
        return Object.keys(files).some(f => f.startsWith(path + `/`));
      }
    },
    glob: async pattern => sorted(Object.keys(files).filter(matcher(pattern))),
    listFiles: async dir => {
      let prefix = dir === "" ? "" : dir + `/`;
      return sorted(Object.keys(files).filter(p => {
        if (p.startsWith(prefix)) {
          return !p.slice(prefix.length).includes("/");
        } else {
          return false;
        }
      }).map(p => p.slice(prefix.length)));
    }
  };
}

let import_ = ((name) => import(name));

function nodeFs(root) {
  let cache = {
    contents: undefined
  };
  let mods = () => {
    let loaded = cache.contents;
    if (loaded !== undefined) {
      return loaded;
    }
    let loaded$1 = (async () => {
      let fs = await import_("node:fs/promises");
      let base;
      if (root !== undefined) {
        if (typeof root === "string") {
          base = root.startsWith("/") ? root : Schema.join(process.cwd(), root);
        } else {
          let url = await import_("node:url");
          base = url.fileURLToPath(root);
        }
      } else {
        base = process.cwd();
      }
      return [
        fs,
        base
      ];
    })();
    cache.contents = loaded$1;
    return loaded$1;
  };
  let absolute = (base, path) => {
    if (path.startsWith("/")) {
      return path;
    } else {
      return Schema.join(base, path);
    }
  };
  return {
    readFile: async path => {
      let match = await mods();
      return await match[0].readFile(absolute(match[1], path), "utf8");
    },
    writeFile: async (path, content) => {
      let match = await mods();
      let fs = match[0];
      let file = absolute(match[1], path);
      await fs.mkdir(Schema.dirname(file), {
        recursive: true
      });
      return await fs.writeFile(file, content, "utf8");
    },
    copy: async (source, output) => {
      let match = await mods();
      let base = match[1];
      let fs = match[0];
      let target = absolute(base, output);
      await fs.mkdir(Schema.dirname(target), {
        recursive: true
      });
      return await fs.cp(absolute(base, source), target, {
        recursive: true
      });
    },
    exists: async path => {
      let match = await mods();
      try {
        await match[0].access(absolute(match[1], path));
        return true;
      } catch (exn) {
        return false;
      }
    },
    glob: async pattern => {
      let match = await mods();
      let base = match[1];
      let entries;
      try {
        entries = await match[0].readdir(base, {
          withFileTypes: true,
          recursive: true
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(e => (e.parentPath + `/` + e.name).slice(base.length + 1 | 0).replace(slashes, "/")).filter(matcher(pattern)).toSorted(Primitive_string.compare);
    },
    listFiles: async dir => {
      let match = await mods();
      let entries;
      try {
        entries = await match[0].readdir(absolute(match[1], dir), {
          withFileTypes: true,
          recursive: false
        });
      } catch (exn) {
        entries = [];
      }
      return entries.filter(__x => __x.isFile()).map(__x => __x.name).toSorted(Primitive_string.compare);
    }
  };
}

function strings(vars) {
  let out = {};
  Object.entries(vars).forEach(param => {
    let v = param[1];
    if (v.TAG !== "Scalar") {
      return;
    }
    out[param[0]] = {
      TAG: "Str",
      _0: v._0
    };
  });
  return out;
}

function lift(front) {
  return Stdlib_Dict.mapValues(front, d => {
    if (d.TAG === "One") {
      return {
        TAG: "Str",
        _0: d._0
      };
    } else {
      return {
        TAG: "Items",
        _0: d._0
      };
    }
  });
}

function infer(path) {
  if (path.endsWith(".md") || path.endsWith(".markdown")) {
    return "md";
  } else if (path.endsWith(".html") || path.endsWith(".htm")) {
    return "none";
  } else {
    return;
  }
}

async function exec(fs, entry, transforms) {
  let cache = {};
  let named = (name, at) => {
    let t = transforms[name];
    if (t !== undefined) {
      return t;
    } else {
      return Schema.fail(at + `: unknown transform "` + name + `" (available: ` + Object.keys(transforms).join(", ") + `)`);
    }
  };
  let parsed = (path, at) => {
    let hit = cache[path];
    if (hit !== undefined) {
      return hit;
    }
    let loading = (async () => {
      if (!await fs.exists(path)) {
        Schema.fail(`Content file not found: ` + path + ` (declared at ` + at + `)`);
      }
      let text = await fs.readFile(path);
      if (!text.startsWith("---\n")) {
        return {
          front: {},
          body: text
        };
      }
      let m = matter.exec(text);
      if (m == null) {
        return Schema.fail(path + `: unterminated frontmatter (missing closing "---" line)`);
      }
      let match = m.slice(1)[0];
      let vars;
      if (match !== undefined) {
        let head = Primitive_option.valFromOption(match);
        vars = head !== undefined ? Schema.front(head, path) : ({});
      } else {
        vars = {};
      }
      return {
        front: vars,
        body: text.slice(m[0].length)
      };
    })();
    cache[path] = loading;
    return loading;
  };
  let content = async (explicit, path, at) => {
    let match = await parsed(path, at);
    let name = Stdlib_Option.orElse(explicit, infer(path));
    if (name !== undefined) {
      return {
        body: match.body,
        transform: named(name, at),
        front: {
          label: `frontmatter (` + path + `)`,
          vars: lift(match.front)
        },
        at: `file ` + path
      };
    } else {
      return Schema.fail(at + `: cannot infer a transform for ` + path + ` — set "transform" (available: ` + Object.keys(transforms).join(", ") + `)`);
    }
  };
  let folder = async (d, at, paths) => {
    let dir = expand(d.dir, paths, [], at + ` dir`);
    let glob = Stdlib_Option.getOr(d.glob, "*.md");
    let names = (await fs.listFiles(dir)).filter(matcher(glob));
    if (names.length === 0) {
      Schema.fail(`No files matching "` + glob + `" in ` + dir + ` (declared at ` + at + `)`);
    }
    let items = await Promise.all(names.map(name => content(d.transform, Schema.join(dir, name), at)));
    return {
      items: items,
      each: Stdlib_Option.getOr(d.each, "{{body}}"),
      at: `dir ` + dir + ` (` + at + `)`
    };
  };
  let scopes = async (vars, label, paths) => {
    let loaded = {};
    let exported = {};
    let owners = {};
    await seq(Object.entries(vars), 0, async param => {
      let v = param[1];
      let name = param[0];
      let at = label + `.` + name;
      switch (v.TAG) {
        case "Scalar" :
          loaded[name] = {
            TAG: "Str",
            _0: v._0
          };
          return;
        case "Scalars" :
          loaded[name] = {
            TAG: "Items",
            _0: v._0
          };
          return;
        case "FileV" :
          let f = v._0;
          let path = expand(f.file, paths, [], at + ` file`);
          let c = await content(f.transform, path, at);
          loaded[name] = {
            TAG: "File",
            _0: c
          };
          Object.entries(c.front.vars).forEach(param => {
            let fname = param[0];
            let owner = owners[fname];
            if (owner !== undefined && owner !== path) {
              Schema.fail(`Frontmatter conflict in ` + label + `: "` + fname + `" defined by both ` + owner + ` and ` + path);
            }
            owners[fname] = path;
            exported[fname] = param[1];
          });
          return;
        case "DirV" :
          loaded[name] = {
            TAG: "Folder",
            _0: await folder(v._0, at, paths)
          };
          return;
        case "ListV" :
          let l = v._0;
          loaded[name] = {
            TAG: "Loop",
            _0: {
              source: l.list,
              each: l.each,
              join: Stdlib_Option.getOr(l.join, ""),
              template: l.template,
              at: at
            }
          };
          return;
        case "PipeV" :
          let p = v._0;
          loaded[name] = {
            TAG: "Piped",
            _0: {
              value: p.value,
              transform: named(p.transform, at),
              at: at
            }
          };
          return;
      }
    });
    let head = {
      label: label,
      vars: loaded
    };
    if (Object.keys(exported).length !== 0) {
      return [
        head,
        {
          label: `frontmatter (` + label + `)`,
          vars: exported
        }
      ];
    } else {
      return [head];
    }
  };
  let chain = async (path, visited, from) => {
    if (visited.includes(path)) {
      Schema.fail(`Base config cycle: ` + Belt_Array.concatMany([
        visited,
        [path]
      ]).join(" -> "));
    }
    if (!await fs.exists(path)) {
      Schema.fail(`Config not found: ` + path + (
        from === "" ? "" : ` (base of ` + from + `)`
      ));
    }
    let config = Schema.parse(await fs.readFile(path), path);
    let base = config.base;
    let rest = base !== undefined ? await chain(base, Belt_Array.concatMany([
        visited,
        [path]
      ]), path) : [];
    return Belt_Array.concatMany([
      [[
          path,
          config
        ]],
      rest
    ]);
  };
  let emit = async (b, globals, paths, at) => {
    let label = at + `.var`;
    let local = Belt_Array.concatMany([
      [{
          label: label,
          vars: strings(b.vars)
        }],
      paths
    ]);
    let all = Belt_Array.concatMany([
      await scopes(b.vars, label, local),
      globals
    ]);
    let finish = async (v, all) => {
      let output = expand(b.output, all, [], at + ` output`);
      return await fs.writeFile(output, grow(v, all, [], at + ` input`));
    };
    let path = b.input;
    switch (path.TAG) {
      case "Text" :
        return await finish({
          TAG: "Str",
          _0: path._0
        }, all);
      case "FileI" :
        let f = path._0;
        let path$1 = expand(f.file, local, [], at + ` input file`);
        let c = await content(f.transform, path$1, at + ` input`);
        return await finish({
          TAG: "File",
          _0: c
        }, Belt_Array.concatMany([
          all,
          [c.front]
        ]));
      case "DirI" :
        return await finish({
          TAG: "Folder",
          _0: await folder(path._0, at + ` input`, local)
        }, all);
      case "Copy" :
        let source = expand(path._0, local, [], at + ` input copy`);
        if (!await fs.exists(source)) {
          Schema.fail(`Copy source not found: ` + source + ` (declared at ` + at + ` input)`);
        }
        return await fs.copy(source, expand(b.output, all, [], at + ` output`));
    }
  };
  let links = await chain(entry, [], "");
  let paths = links.map(param => ({
    label: `var (` + param[0] + `)`,
    vars: strings(param[1].vars)
  }));
  let globals = [];
  await seq(links, 0, async param => {
    let loaded = await scopes(param[1].vars, `var (` + param[0] + `)`, paths);
    loaded.forEach(s => {
      globals.push(s);
    });
  });
  let match = links[0];
  await Promise.all(match[1].build.map((b, i) => emit(b, globals, paths, `build[` + i.toString() + `]`)));
}

async function run(options) {
  let fs = options.fs;
  let fs$1 = fs !== undefined ? fs : nodeFs(undefined);
  let configs = await fs$1.glob(options.glob);
  if (configs.length === 0) {
    Schema.fail(`No config files match "` + options.glob + `"`);
  }
  let transforms = Object.assign(Object.assign({}, defaults), Stdlib_Option.getOr(options.transform, {}));
  await Promise.all(configs.toSorted(Primitive_string.compare).map(config => exec(fs$1, config, transforms)));
}

export {
  run,
  makeMemoryFileSystem,
  nodeFs,
}
/* special Not a pure module */
